### ISSUE TITLE
Crash with data importer

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#1471]
I was opening an Importer that has a data package. I had added 2 new csv files that the data package could have picked up. But that makes the Toolbox crash every time I try to open the importer. Happens in the FlexTool3 project with this commit: c62eb3bf30fd782c8854b9329434da9aa01e6c29

```
Traceback (most recent call last):
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\tabulator\stream.py", line 744, in __extract_sample
    row_number, headers, row = next(self.__parser.extended_rows)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\tabulator\parsers\csv.py", line 114, in __iter_extended_rows
    for row_number, item in enumerate(items, start=1):
ValueError: I/O operation on closed file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\data\spine-items\spine_items\importer\connection_manager.py", line 350, in tables
    raise error
  File "C:\data\spine-items\spine_items\importer\connection_manager.py", line 346, in tables
    tables = self._connection.get_tables()
  File "C:\data\SpineDB_api\spinedb_api\spine_io\importers\datapackage_reader.py", line 67, in get_tables
    resource.infer()
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\datapackage\resource.py", line 538, in infer
    descriptor['schema'] = self.__get_table().infer(**options)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\tableschema\table.py", line 383, in infer
    with self.__stream as stream:
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\tabulator\stream.py", line 288, in __enter__
    self.open()
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\tabulator\stream.py", line 424, in open
    self.__extract_sample()
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\tabulator\stream.py", line 756, in __extract_sample
    raise exceptions.SourceError(str(error))
tabulator.exceptions.SourceError: I/O operation on closed file.

Process finished with exit code -1073740791 (0xC0000409)

```

**Comment by soininen** [comment]
I couldn't reproduce this issue.
