### ISSUE TITLE
Support jupyter-client 7.x or greater

### ISSUE THREAD

**Issue by PekkaSavolainen** [spine-tools/Spine-Toolbox#1474]
Jupyter Console execution does not work with jupyter-client version 7.x. The fix for now is to require jupyter-client < 7.0. E.g. jupyter-client 6.1.12 works.

Traceback after clicking 'play':
```
(toolbox38) C:\data\GIT\SPINETOOLBOX>python spinetoolbox
Exception in thread Thread-18:
Traceback (most recent call last):
  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\spine_engine\spine_engine.py", line 474, in _execute_item_filtered
    item_finish_state = item.execute(filtered_forward_resources, filtered_backward_resources)
  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\spine_items\tool\executable_item.py", line 425, in execute
    return_code = self._tool_instance.execute()
  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\spine_items\tool\tool_instance.py", line 231, in execute
Traceback (most recent call last):
  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\spine_items\tool\tool.py", line 509, in _setup_jupyter_console
    ret = self.exec_mngr.run_until_complete()
  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\spine_engine\execution_managers\kernel_execution_manager.py", line 187, in run_until_complete
    self.console = self._toolbox.make_jupyter_console(self, kernel_name, connection_file)
  File "c:\data\git\spinetoolbox\spinetoolbox\ui_main.py", line 2224, in make_jupyter_console
    self._kernel_client.start_channels()
  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\jupyter_client\client.py", line 286, in start_channels
    console.connect_to_kernel(kernel_name, connection_file)
self.iopub_channel.start()  File "c:\data\git\spinetoolbox\spinetoolbox\widgets\jupyter_console_widget.py", line 276, in connect_to_kernel

    self._replace_client()  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\jupyter_client\client.py", line 344, in iopub_channel

      File "c:\data\git\spinetoolbox\spinetoolbox\widgets\jupyter_console_widget.py", line 258, in _replace_client
socket = self.connect_iopub()
kc.start_channels()  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\jupyter_client\connect.py", line 628, in connect_iopub

  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\qtconsole\kernel_mixins.py", line 47, in start_channels
    sock = self._create_connected_socket("iopub", identity=identity)
  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\jupyter_client\connect.py", line 618, in _create_connected_socket
    sock = self.context.socket(socket_type)
  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\zmq\sugar\context.py", line 235, in socket
    super().start_channels(*args, **kw)
  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\jupyter_client\threaded.py", line 274, in start_channels
    self.shell_channel._inspect = self._check_kernel_info_reply
  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\jupyter_client\client.py", line 334, in shell_channel
    socket = self.connect_shell(identity=self.session.bsession)
  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\jupyter_client\connect.py", line 634, in connect_shell
    return self._create_connected_socket("shell", identity=identity)
  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\jupyter_client\connect.py", line 618, in _create_connected_socket
    s = self._socket_class(self, socket_type, **kwargs)
sock = self.context.socket(socket_type)  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\zmq\_future.py", line 150, in __init__

  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\zmq\sugar\context.py", line 235, in socket
    s = self._socket_class(self, socket_type, **kwargs)
  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\zmq\_future.py", line 150, in __init__
    self._init_io_state()
self._init_io_state()  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\zmq\asyncio.py", line 51, in _init_io_state

  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\zmq\asyncio.py", line 51, in _init_io_state
    self.io_loop.add_reader(self._fd, lambda: self._handle_events(0, 0))
  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\asyncio\events.py", line 501, in add_reader
self.io_loop.add_reader(self._fd, lambda: self._handle_events(0, 0))
  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
raise NotImplementedError
NotImplementedError
Exception ignored in: <function Socket.__del__ at 0x0000020190A4DDC0>
Traceback (most recent call last):
  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\zmq\sugar\socket.py", line 66, in __del__
    self.close()
  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\zmq\_future.py", line 168, in close
    self._clear_io_state()
  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\site-packages\zmq\asyncio.py", line 58, in _clear_io_state
    self.io_loop.remove_reader(self._fd)
  File "C:\Users\ttepsa\.conda\envs\toolbox38\lib\asyncio\events.py", line 504, in remove_reader
    raise NotImplementedError
NotImplementedError:
```

**Comment by jkiviluo** [comment]
@PekkaSavolainen Is this issue still alive?

**Comment by PekkaSavolainen** [comment]
Yes, but it's not really a bug. We simply don't support jupyter-client >= 7.0. I'll update the title.

**Comment by PekkaSavolainen** [comment]
Duplicate of #1495.
