### ISSUE TITLE
Exporter excel writer, invalid character for a sheet name

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#1561]
I have a mapping where I set the alternative name to the table name position. The alternative has a time-stamp because it's from a 'results' DB, so it has the `:` character which is invalid for a sheet name. I propose we just replace invalid characters by something, like `*`.

```
Process ReturningProcess-1:
Traceback (most recent call last):
  File "/home/manuel/miniconda3/envs/spinetoolbox/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/manuel/Codes/spine/spine-engine/spine_engine/utils/returning_process.py", line 41, in run
    result = self._target(*self._args, **self._kwargs)
  File "/home/manuel/Codes/spine/spine-items/spine_items/exporter/do_work.py", line 71, in do_work
    write(database_map, writer, *mappings, empty_data_header=header_always)
  File "/home/manuel/Codes/spine/Spine-Database-API/spinedb_api/spine_io/exporters/writer.py", line 44, in write
    write_more = writer.write_row(row)
  File "/home/manuel/Codes/spine/Spine-Database-API/spinedb_api/spine_io/exporters/excel_writer.py", line 91, in write_row
    self._set_current_sheet()
  File "/home/manuel/Codes/spine/Spine-Database-API/spinedb_api/spine_io/exporters/excel_writer.py", line 79, in _set_current_sheet
    self._current_sheet = self._workbook.create_sheet(self._next_table_name)
  File "/home/manuel/miniconda3/envs/spinetoolbox/lib/python3.8/site-packages/openpyxl/workbook/workbook.py", line 197, in create_sheet
    new_ws = Worksheet(parent=self, title=title)
  File "/home/manuel/miniconda3/envs/spinetoolbox/lib/python3.8/site-packages/openpyxl/worksheet/worksheet.py", line 97, in __init__
    _WorkbookChild.__init__(self, parent, title)
  File "/home/manuel/miniconda3/envs/spinetoolbox/lib/python3.8/site-packages/openpyxl/workbook/child.py", line 47, in __init__
    self.title = title or self._default_title
  File "/home/manuel/miniconda3/envs/spinetoolbox/lib/python3.8/site-packages/openpyxl/workbook/child.py", line 93, in title
    raise ValueError(msg)
ValueError: Invalid character : found in sheet title
```

**Comment by jkiviluo** [comment]
I guess that's fine. However, asterix feels bit dangerous since it can have special meaning. Underscore should be safer.

**Comment by jkiviluo** [comment]
@manuelma Looks like this is done?

**Comment by manuelma** [comment]
It looks like :)
