### ISSUE TITLE
TB when opening exporter spec without a DB set in the input Data Store

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#1565]
```
Traceback (most recent call last):
  File "/home/manuel/Codes/spine/Spine-Toolbox/spinetoolbox/helpers.py", line 129, in new_function
    return func(*args, **kwargs)
  File "/home/manuel/Codes/spine/spine-items/spine_items/exporter/widgets/preview_updater.py", line 470, in run
    db_map = DatabaseMapping(self._url)
  File "/home/manuel/Codes/spine/Spine-Database-API/spinedb_api/db_mapping.py", line 44, in __init__
    super().__init__(*args, **kwargs)
  File "/home/manuel/Codes/spine/Spine-Database-API/spinedb_api/db_mapping_add_mixin.py", line 32, in __init__
    super().__init__(*args, **kwargs)
  File "/home/manuel/Codes/spine/Spine-Database-API/spinedb_api/db_mapping_commit_mixin.py", line 33, in __init__
    super().__init__(*args, **kwargs)
  File "/home/manuel/Codes/spine/Spine-Database-API/spinedb_api/db_mapping_base.py", line 80, in __init__
    self.engine = self.create_engine(self.sa_url, upgrade=upgrade, create=create)
  File "/home/manuel/Codes/spine/Spine-Database-API/spinedb_api/db_mapping_base.py", line 277, in create_engine
    raise SpineDBAPIError(
spinedb_api.exception.SpineDBAPIError: Unable to determine db revision. Please check that

	sqlite:////home/manuel/Codes/spine/Spine-Toolbox/projects/Hydrilyte/.spinetoolbox/items/output_db/input_hydrilyte_out.sqlite

is the URL of a valid Spine db.
```

I believe we'd just need to catch the exception and put it into Event log or something?

**Comment by soininen** [comment]
Looks like this issue has been fixed one way or another already.
