### ISSUE TITLE
Pivot editor crashes Toolbox

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#1629]
I can crash the toolbox by writing into an empty pivot table.
- Trying to add new unitGroup
- after writing unitGroup name, press Tab
- a crash

![image](https://user-images.githubusercontent.com/40472544/146335595-776005a3-7592-4af1-b0c1-4f6fe602285a.png)

```
Traceback (most recent call last):
  File "c:\data\spinetoolbox\spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 1423, in filterAcceptsColumn
    index = self.sourceModel().model._column_data_header[source_column - self.sourceModel().headerColumnCount()]
IndexError: list index out of range
Traceback (most recent call last):
  File "c:\data\spinetoolbox\spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 1423, in filterAcceptsColumn
    index = self.sourceModel().model._column_data_header[source_column - self.sourceModel().headerColumnCount()]
IndexError: list index out of range
```

**Comment by jkiviluo** [comment]
Seems to work nowadays.
