### ISSUE TITLE
Importing a lacking datapackage gets stuck.

### ISSUE THREAD

**Issue by Tasqu** [spine-tools/Spine-Toolbox#1638]
When importing a datapackage, if the datapackage is missing any files that should be read according to the importer specification, toolbox seems to get stuck doing the import indefinitely with the following traceback.
```
(toolboxatlite) C:\data\Desktop>CALL python -m spinetoolbox
Process ReturningProcess-1:
Traceback (most recent call last):
  File "C:\Users\TRTOPI\Miniconda3\envs\toolboxatlite\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\data\spine\spine-toolbox\src\spine-engine\spine_engine\utils\returning_process.py", line 46, in run
    result = self._target(*self._args, **self._kwargs)
  File "c:\data\spine\spine-toolbox\src\spine-items\spine_items\importer\do_work.py", line 65, in do_work
    data, errors = connector.get_mapped_data(
  File "c:\data\spine\spine-toolbox\src\spinedb-api\spinedb_api\spine_io\importers\reader.py", line 126, in get_mapped_data
    data_source, header = self.get_data_iterator(table, options, table_max_rows)
  File "c:\data\spine\spine-toolbox\src\spinedb-api\spinedb_api\spine_io\importers\datapackage_reader.py", line 103, in get_data_iterator
    resource.infer()
  File "C:\Users\TRTOPI\Miniconda3\envs\toolboxatlite\lib\site-packages\datapackage\resource.py", line 526, in infer
    with self.raw_iter(stream=True) as stream:
  File "C:\Users\TRTOPI\Miniconda3\envs\toolboxatlite\lib\site-packages\datapackage\resource.py", line 470, in raw_iter
    filelike = io.open(self.source, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\TRTOPI\\OneDrive - Teknologian Tutkimuskeskus VTT\\_PROJEKTIT\\FlexiB\\_DATA\\finnish_default_structural_data\\data\\ventilation.csv'
```

**Comment by soininen** [comment]
It seems this issue doesn't exist anymore.
