### ISSUE TITLE
Traceback when purging database

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#1713]
I got this Traceback when purging a database that has tools and features defined. I tried to exclude tools, features and tool features from the purge but maybe didn't uncheck all the necessary boxes.

```
Traceback (most recent call last):
  File "C:\data\src\toolbox\spinetoolbox\spine_db_signaller.py", line 332, in receive_tool_feature_methods_removed
    self._call_in_listeners("receive_tool_feature_methods_removed", db_map_data)
  File "C:\data\src\toolbox\spinetoolbox\helpers.py", line 119, in new_function
    return func(*args, **kwargs)
  File "C:\data\src\toolbox\spinetoolbox\spine_db_signaller.py", line 366, in _call_in_listeners
    method({db_map: data})
  File "C:\data\src\toolbox\spinetoolbox\spine_db_editor\widgets\tree_view_mixin.py", line 382, in receive_tool_feature_methods_removed
    self.tool_feature_model.remove_tool_feature_methods(db_map_data)
  File "C:\data\src\toolbox\spinetoolbox\spine_db_editor\mvcmodels\tool_feature_model.py", line 185, in remove_tool_feature_methods
    for root_item, items in self._tool_feature_methods_per_root(db_map_data).items():
  File "C:\data\src\toolbox\spinetoolbox\spine_db_editor\mvcmodels\tool_feature_model.py", line 125, in _tool_feature_methods_per_root
    tool_feat_leaf_item = next(
  File "C:\data\src\toolbox\spinetoolbox\spine_db_editor\mvcmodels\tool_feature_model.py", line 129, in <genexpr>
    for child in tool_leaf_item.child(0).children
AttributeError: 'NoneType' object has no attribute 'children'
```

**Comment by jkiviluo** [comment]
Maybe not an issue anymore? I will anyway move to 1.0 for further inspection.

**Comment by soininen** [comment]
I tried to reproduce this one but couldn't, and with the previous "more async" changes, this might be gone for good.
