### ISSUE TITLE
Traceback in Manage relationships dialog

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#1855]
Adding relationships with the >> button gives a Traceback:
```
Traceback (most recent call last):
  File "spinetoolbox\spine_db_editor\widgets\add_items_dialogs.py", line 723, in add_relationships
    self.new_items_model.insertRows(0, count)
  File "spinetoolbox\mvcmodels\minimal_table_model.py", line 202, in insertRows
    self.beginInsertRows(parent, row, row + count - 1)
RuntimeError: Internal C++ object (MinimalTableModel) already deleted.
```

Reported by @Tasqu

**Comment by soininen** [comment]
Looks like this has been fixed already.
