### ISSUE TITLE
Traceback when purging tool/feature/methods

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#1906]
When purging tool feature methods (or one/some of those, not entirely sure...), I got this Traceback repeatedly:

```
Traceback (most recent call last):
  File "spinetoolbox\mvcmodels\minimal_tree_model.py", line 318, in data
    return item.data(index.column(), role)
  File "spinetoolbox\spine_db_editor\mvcmodels\tree_item_utility.py", line 98, in data
    return super().data(column, role)
  File "spinetoolbox\spine_db_editor\mvcmodels\tree_item_utility.py", line 306, in data
    data = self.item_data.get(self.header_data(column))
  File "spinetoolbox\spine_db_editor\mvcmodels\tool_feature_item.py", line 88, in item_data
    name = self.model.make_feature_name(item_data["entity_class_name"], item_data["parameter_definition_name"])
  File "spinetoolbox\spine_db_editor\mvcmodels\tool_feature_model.py", line 50, in make_feature_name
    return entity_class_name + "/" + parameter_definition_name
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by soininen** [comment]
I cannot reproduce this one. Perhaps it got fixed with the "more asynchronous fetching" refactoring?
