### ISSUE TITLE
Traceback when adding/removing scenarios in Database editor

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#1926]
Not sure if these are exact steps to get the Traceback below but this is what I did:
1. Create a new sqlite database
2. Open Database editor
3. Add a scenario
4. commit
5. Close the Database editor

```
Traceback (most recent call last):
  File "Cspinetoolbox\helpers.py", line 121, in new_function
    return func(*args, **kwargs)
  File "spinetoolbox\fetch_parent.py", line 96, in _apply_pending_changes
    self.handle_items_added({db_map: data})
  File "spinetoolbox\fetch_parent.py", line 261, in handle_items_added
    self._handle_items_added(db_map_data)
  File "spinetoolbox\spine_db_editor\mvcmodels\tree_item_utility.py", line 205, in handle_items_added
    self.insert_children_sorted(children_committed)
  File "spinetoolbox\spine_db_editor\mvcmodels\tree_item_utility.py", line 136, in insert_children_sorted
    if not super().insert_children(pos, chunk):
  File "spinetoolbox\mvcmodels\minimal_tree_model.py", line 140, in insert_children
    self.model.beginInsertRows(self.index(), position, position + len(children) - 1)
  File "spinetoolbox\mvcmodels\minimal_tree_model.py", line 118, in index
    return self.model.index_from_item(self)
  File "spinetoolbox\mvcmodels\minimal_tree_model.py", line 295, in index_from_item
    return self.createIndex(item.child_number(), 0, item)
RuntimeError: Internal C++ object (AlternativeScenarioModel) already deleted.
```

**Comment by soininen** [comment]
I got very similar Traceback in Database editor when removing scenarios (just selecting the Remove action from the popup menu, no need to commit):
```
Traceback (most recent call last):
  File "C:\Users\ajsanttij\Sources\Spine-Toolbox\spinetoolbox\helpers.py", line 121, in new_function
    return func(*args, **kwargs)
  File "C:\Users\ajsanttij\Sources\Spine-Toolbox\spinetoolbox\fetch_parent.py", line 102, in _apply_pending_changes
    self.handle_items_removed({db_map: data})
  File "C:\Users\ajsanttij\Sources\Spine-Toolbox\spinetoolbox\fetch_parent.py", line 266, in handle_items_removed
    self._handle_items_removed(db_map_data)
  File "C:\Users\ajsanttij\Sources\Spine-Toolbox\spinetoolbox\spine_db_editor\mvcmodels\tree_item_utility.py", line 215, in handle_items_removed
    self.remove_children(row, 1)
  File "C:\Users\ajsanttij\Sources\Spine-Toolbox\spinetoolbox\mvcmodels\minimal_tree_model.py", line 178, in remove_children
    self.model.beginRemoveRows(self.index(), first, last)
  File "C:\Users\ajsanttij\Sources\Spine-Toolbox\spinetoolbox\mvcmodels\minimal_tree_model.py", line 118, in index
    return self.model.index_from_item(self)
  File "C:\Users\ajsanttij\Sources\Spine-Toolbox\spinetoolbox\mvcmodels\minimal_tree_model.py", line 295, in index_from_item
    return self.createIndex(item.child_number(), 0, item)
RuntimeError: Internal C++ object (AlternativeScenarioModel) already deleted.
```

**Comment by manuelma** [comment]
The steps to reproduce are actually open db editor, close it, open again and add anything. Some of the UI items from the closed db editor are still reacting to changes in the DB. We just need to clean them up connecting the destroyed signal of the corresponding model to the tear_down() method. Will do that now.
