### ISSUE TITLE
Pivot table mapping not work well

### ISSUE THREAD

**Issue by nnhjy** [spine-tools/Spine-Toolbox#2017]
Using pivot table mappings to import `array` values causes some unexpected bad results: (. See the sample below.
![1677866719494](https://user-images.githubusercontent.com/43530784/222794814-6ddedd78-d289-4cdd-ab67-048e2cda18b5.png)
![1677866750586](https://user-images.githubusercontent.com/43530784/222794899-c86a0440-e2e8-4040-9df5-0bfb3e289b67.png)

**Comment by nnhjy** [comment]
One more issue regarding the pivot table: with the following mapping I get an error saying "Not all array's values are of the same type."
![1677867656849](https://user-images.githubusercontent.com/43530784/222797769-27414f0e-83c1-4ca5-b49c-ba5d261e8b7e.png)
However, no errors occur if I do not use the pivot table for mapping.

**Comment by jkiviluo** [comment]
I can replicate a lot of issues when trying to do something like this. Attached is a small example. I think the root cause is that the importer does not handle the situations where the rows are not mapped in the specification (a bit counterintuitively this happens when something is mapped to a specific column - there is no mapping to a column in the spec). In the last example of @nnhjy, headers are mapped (which is the same as mapping object names to row 1 in a headerless spec). The importer then assumes that the table has pivoted values - but it shouldn't since the specification does not say how to map the rows. I guess it could be assumed from this being an 'array' mapping (where a row is mapped to objects but no column is mapped, so columns must contain the arrays). However, the same issue persists, if 'array' is changed to 'constant'.

Fundamentally, the issue is that we are treating column direction different from row direction. This may take bit of time to fix, so the workaround is to either change direction in the original data (make the arrays lay on rows) or to add an index column and use a map instead of an array.

[import_array.zip](https://github.com/spine-tools/Spine-Toolbox/files/10887748/import_array.zip)

**Comment by soininen** [comment]
> with the following mapping I get an error saying "Not all array's values are of the same type."

@nnhjy, would it be possible to provide me the data so I can reproduce this?

**Comment by nnhjy** [comment]
Sure, try this: [sample.xlsx](https://github.com/spine-tools/Spine-Toolbox/files/10960061/sample.xlsx).

**Comment by soininen** [comment]
Thanks for the file @nnhjy! The file seems to work fine after the PR above. However, what I really wanted to try out here was to reproduce the problem where you get the "Not all array's values are of the same type." error so I should have been more clear about that. Do you have test data that generates that particular error?

**Comment by nnhjy** [comment]
Oh sorry @soininen it did produce the issue yesterday, which somehow disappears today. Things seem to get a bit different. Please try this out 
[hydro-ror.xlsx](https://github.com/spine-tools/Spine-Toolbox/files/10970811/hydro-ror.xlsx) with a mapping as below
![1678809808433](https://user-images.githubusercontent.com/43530784/225064986-186833c1-6c46-49dc-87b9-0859227886b4.png)
There are two issues now:
1) "Not all array's values are of the same type." With a one-hour investigation, I finally found out that this seems to be caused by the "0.00" value at the bottom row of the data file.
2) If you remove the last row to make the importer work, you would probably see that the first column of data is ignored. It smells like the importer treats the first column as some indices rather than data.

And my toolbox lies at the master branch commit [01c97dc1759b2b9f14bb5130c2e87a96294ecf17](https://github.com/spine-tools/Spine-Toolbox/commit/01c97dc1759b2b9f14bb5130c2e87a96294ecf17).

**Comment by soininen** [comment]
> "Not all array's values are of the same type." With a one-hour investigation, I finally found out that this seems to be caused by the "0.00" value at the bottom row of the data file.

With the new data file I was also able to reproduce and fix this error. Thank you for the test data!

> If you remove the last row to make the importer work, you would probably see that the first column of data is ignored. It smells like the importer treats the first column as some indices rather than data.

I could not reproduce this one. I tried to delete the last row in Excel (in two different ways) as well as exclude it in Importer by setting Max rows option. However, as far as I can tell the data was importer correctly with all four objects in the target database. Can you provide more information on this?

**Comment by soininen** [comment]
Please also note that the fixes have been in Spine-Database-API; you'll need to update `spinedb_api` package or Toolbox requirements to get the them.

**Comment by nnhjy** [comment]
It does seem to work now with the `toolbox` and `db-api` just pulled. Many thanks @soininen! Shall we close the issue for now or keep it open? I feel similar issues might come around from time to time (like Juha mentioned above). When importing the same file, I've spotted some error messages which have yet caused fatal outcomes.
```
(env3.10-Spine) PS C:\Tools\Spine\Toolbox> spinetoolbox
Exception in thread Thread-72 (_execute_item_filtered):
Exception in thread Thread-73 (_execute_item_filtered):
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Tools\Python\Python3-10\lib\threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-74 (_execute_item_filtered):
  File "C:\Tools\Python\Python3-10\lib\threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-76 (_execute_item_filtered):
Exception in thread Thread-75 (_execute_item_filtered):
Traceback (most recent call last):
  File "C:\Tools\Python\Python3-10\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    self.run()
  File "C:\Tools\Python\Python3-10\lib\threading.py", line 953, in run
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Tools\Python\Python3-10\lib\threading.py", line 953, in run
  File "C:\Tools\Python\Python3-10\lib\threading.py", line 1016, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "C:\Tools\Python\Python3-10\lib\threading.py", line 1016, in _bootstrap_inner
  File "C:\Tools\Spine\Toolbox\spine-engine\spine_engine\spine_engine.py", line 562, in _execute_item_filtered
    self.run()
  File "C:\Tools\Python\Python3-10\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    output_resources = item.output_resources(ED.FORWARD)
    self.run()
    self.run()
  File "C:\Tools\Python\Python3-10\lib\threading.py", line 953, in run
  File "C:\Tools\Spine\Toolbox\spine-engine\spine_engine\spine_engine.py", line 562, in _execute_item_filtered
  File "C:\Tools\Spine\Toolbox\spine-engine\spine_engine\project_item\executable_item_base.py", line 165, in output_resources
    self._target(*self._args, **self._kwargs)
  File "C:\Tools\Spine\Toolbox\spine-engine\spine_engine\spine_engine.py", line 562, in _execute_item_filtered
  File "C:\Tools\Python\Python3-10\lib\threading.py", line 953, in run
    output_resources = item.output_resources(ED.FORWARD)
    return {
  File "C:\Tools\Spine\Toolbox\spine-items\spine_items\exporter\executable_item.py", line 208, in _output_resources_forward
    self._target(*self._args, **self._kwargs)
  File "C:\Tools\Spine\Toolbox\spine-engine\spine_engine\project_item\executable_item_base.py", line 165, in output_resources
    self._target(*self._args, **self._kwargs)
  File "C:\Tools\Spine\Toolbox\spine-engine\spine_engine\spine_engine.py", line 562, in _execute_item_filtered
    output_resources = item.output_resources(ED.FORWARD)
  File "C:\Tools\Spine\Toolbox\spine-engine\spine_engine\spine_engine.py", line 562, in _execute_item_filtered
  File "C:\Tools\Spine\Toolbox\spine-engine\spine_engine\project_item\executable_item_base.py", line 165, in output_resources
    return {
  File "C:\Tools\Spine\Toolbox\spine-items\spine_items\exporter\executable_item.py", line 208, in _output_resources_forward
    for label, output_files in self._result_files.items():
    return {
    output_resources = item.output_resources(ED.FORWARD)
AttributeError: 'NoneType' object has no attribute 'items'
    output_resources = item.output_resources(ED.FORWARD)
    for label, output_files in self._result_files.items():
  File "C:\Tools\Spine\Toolbox\spine-engine\spine_engine\project_item\executable_item_base.py", line 165, in output_resources
  File "C:\Tools\Spine\Toolbox\spine-engine\spine_engine\project_item\executable_item_base.py", line 165, in output_resources
AttributeError: 'NoneType' object has no attribute 'items'
  File "C:\Tools\Spine\Toolbox\spine-items\spine_items\exporter\executable_item.py", line 208, in _output_resources_forward
    return {
    return {
  File "C:\Tools\Spine\Toolbox\spine-items\spine_items\exporter\executable_item.py", line 208, in _output_resources_forward
  File "C:\Tools\Spine\Toolbox\spine-items\spine_items\exporter\executable_item.py", line 208, in _output_resources_forward
    for label, output_files in self._result_files.items():
AttributeError: 'NoneType' object has no attribute 'items'
    for label, output_files in self._result_files.items():
AttributeError: 'NoneType' object has no attribute 'items'
    for label, output_files in self._result_files.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by soininen** [comment]
> Shall we close the issue for now or keep it open?

I prefer opening new issues unless there is clear indication that a problem is linked to an existing issue or its attempted fix. Otherwise the discussion gets easily derailed and it becomes difficult to follow what has been fixed and what still needs fixing. For example, the "Not all array's values are of the same type." error was in fact caused by a different bug (or maybe it was a feature :) than the original issue in the description. Similarly, the Traceback you quoted seems to come from Exporter, not Importer. I can open a new issue for that.
