### ISSUE TITLE
Too many open files when running a workflow multiple times.

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#2019]
Running a workflow multiple times might result in the below, as well as execution no longer working. The obvious reason is we don't shutdown multiprocess.Manager objects every time after we're done with them. Will fix.

```
Exception in thread Thread-1421:
Traceback (most recent call last):
  File "/home/manuel/miniconda3/envs/spinetoolbox/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/manuel/miniconda3/envs/spinetoolbox/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/manuel/Codes/spine/spine-engine/spine_engine/spine_engine.py", line 559, in _execute_item_filtered
    item.exclude_execution(filtered_forward_resources, filtered_backward_resources, item_lock)
  File "/home/manuel/Codes/spine/spine-items/spine_items/tool/executable_item.py", line 497, in exclude_execution
    super().exclude_execution(forward_resources, backward_resources, lock)
  File "/home/manuel/Codes/spine/spine-items/spine_items/db_writer_executable_item_base.py", line 29, in exclude_execution
    resource.quick_db_checkout()
  File "/home/manuel/Codes/spine/spine-engine/spine_engine/project_item/project_item_resource.py", line 101, in quick_db_checkout
    quick_db_checkout(db_server_manager_queue, ordering)
  File "/home/manuel/Codes/spine/Spine-Database-API/spinedb_api/spine_db_server.py", line 563, in quick_db_checkout
    _ManagerRequestHandler(server_manager_queue).quick_db_checkout(ordering)
  File "/home/manuel/Codes/spine/Spine-Database-API/spinedb_api/spine_db_server.py", line 229, in quick_db_checkout
    return self._run_request("quick_db_checkout", ordering)
  File "/home/manuel/Codes/spine/Spine-Database-API/spinedb_api/spine_db_server.py", line 204, in _run_request
    output_queue = mp.Manager().Queue()
  File "/home/manuel/miniconda3/envs/spinetoolbox/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/home/manuel/miniconda3/envs/spinetoolbox/lib/python3.8/multiprocessing/managers.py", line 579, in start
    self._process.start()
  File "/home/manuel/miniconda3/envs/spinetoolbox/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/manuel/miniconda3/envs/spinetoolbox/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/manuel/miniconda3/envs/spinetoolbox/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/manuel/miniconda3/envs/spinetoolbox/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
```

**Comment by soininen** [comment]
@manuelma Wasn't this closed by the PR in Spine-Engine?

**Comment by soininen** [comment]
Yes, sorry, I meant Spine-DB-API. We indeed use multiprocess manager in Engine as well. Good to hear you're checking that as well!
