### ISSUE TITLE
"add relationship" button in `Manage relationships` not work

### ISSUE THREAD

**Issue by nnhjy** [spine-tools/Spine-Toolbox#2020]
![1678354799194](https://user-images.githubusercontent.com/43530784/223982077-b72ba27a-1956-4184-90c8-8028652e7099.png)
The "green plus" icon does not add the selected relationship, with an error in the terminal:
```
Traceback (most recent call last):
  File "C:\Tools\Spine\Toolbox\Spine-Toolbox\spinetoolbox\spine_db_editor\widgets\add_items_dialogs.py", line 718, in add_relationships
    to_add = list(set(candidate) - set(existing))
TypeError: unhashable type: 'list'
```

**Comment by nnhjy** [comment]
![1678466904888](https://user-images.githubusercontent.com/43530784/224374452-e34d39f5-511a-46f1-976f-03d7b913c34d.png)
The green plus button works but no response when clicking the "OK" button:
```
Traceback (most recent call last):
  File "C:\Tools\Spine\Toolbox\Spine-Toolbox\spinetoolbox\spine_db_editor\widgets\add_items_dialogs.py", line 787, in accept
    keys_to_remove = set(self.relationship_ids) - set(self.existing_items_model._main_data)
TypeError: unhashable type: 'list'
```
