### ISSUE TITLE
Traceback when executing exporter

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2037]
Looks like executing Exporter may produce a Traceback:

```
Exception in thread Thread-72 (_execute_item_filtered):
Exception in thread Thread-73 (_execute_item_filtered):
Traceback (most recent call last):
Traceback (most recent call last):
  File "lib\threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-74 (_execute_item_filtered):
  File "lib\threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-76 (_execute_item_filtered):
Exception in thread Thread-75 (_execute_item_filtered):
Traceback (most recent call last):
  File "lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    self.run()
  File "lib\threading.py", line 953, in run
Traceback (most recent call last):
Traceback (most recent call last):
  File "lib\threading.py", line 953, in run
  File "lib\threading.py", line 1016, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "lib\threading.py", line 1016, in _bootstrap_inner
  File "spine-engine\spine_engine\spine_engine.py", line 562, in _execute_item_filtered
    self.run()
  File "lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    output_resources = item.output_resources(ED.FORWARD)
    self.run()
    self.run()
  File "lib\threading.py", line 953, in run
  File "spine-engine\spine_engine\spine_engine.py", line 562, in _execute_item_filtered
  File "spine-engine\spine_engine\project_item\executable_item_base.py", line 165, in output_resources
    self._target(*self._args, **self._kwargs)
  File "spine-engine\spine_engine\spine_engine.py", line 562, in _execute_item_filtered
  File "lib\threading.py", line 953, in run
    output_resources = item.output_resources(ED.FORWARD)
    return {
  File "spine-items\spine_items\exporter\executable_item.py", line 208, in _output_resources_forward
    self._target(*self._args, **self._kwargs)
  File "spine-engine\spine_engine\project_item\executable_item_base.py", line 165, in output_resources
    self._target(*self._args, **self._kwargs)
  File "spine-engine\spine_engine\spine_engine.py", line 562, in _execute_item_filtered
    output_resources = item.output_resources(ED.FORWARD)
  File "spine-engine\spine_engine\spine_engine.py", line 562, in _execute_item_filtered
  File "spine-engine\spine_engine\project_item\executable_item_base.py", line 165, in output_resources
    return {
  File "spine-items\spine_items\exporter\executable_item.py", line 208, in _output_resources_forward
    for label, output_files in self._result_files.items():
    return {
    output_resources = item.output_resources(ED.FORWARD)
AttributeError: 'NoneType' object has no attribute 'items'
    output_resources = item.output_resources(ED.FORWARD)
    for label, output_files in self._result_files.items():
  File "spine-engine\spine_engine\project_item\executable_item_base.py", line 165, in output_resources
  File "spine-engine\spine_engine\project_item\executable_item_base.py", line 165, in output_resources
AttributeError: 'NoneType' object has no attribute 'items'
  File "spine-items\spine_items\exporter\executable_item.py", line 208, in _output_resources_forward
    return {
    return {
  File "spine-items\spine_items\exporter\executable_item.py", line 208, in _output_resources_forward
  File "spine-items\spine_items\exporter\executable_item.py", line 208, in _output_resources_forward
    for label, output_files in self._result_files.items():
AttributeError: 'NoneType' object has no attribute 'items'
    for label, output_files in self._result_files.items():
AttributeError: 'NoneType' object has no attribute 'items'
    for label, output_files in self._result_files.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

Reported by @nnhjy in #2017

**Comment by PiispaH** [comment]
@nnhjy Do you have a reliable way to replicate this Traceback? If so how can it be done?

**Comment by nnhjy** [comment]
Hi @PiispaH , thanks for getting back. I hope [this comment](https://github.com/spine-tools/Spine-Toolbox/issues/2017#issuecomment-1468403233) provides a way to reproduce the issue.

**Comment by PiispaH** [comment]
@nnhjy thanks, since the Traceback is coming from an Exporter and not an Importer, it may not even have anything to do with the Importer specification. This might be a problem on the Exporter's side and therefore would probably also require the Exporter specification used to replicate this.

**Comment by soininen** [comment]
This has been fixed in PR https://github.com/spine-tools/spine-items/pull/108.
