### ISSUE TITLE
Traceback when creating the entity graph in PySide6 6.5.0

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#2077]
For some reason it doesn't like the call to the QRunnable constructor as before?

```
Traceback (most recent call last):
  File "/home/manuel/Codes/spine/Spine-Toolbox/spinetoolbox/spine_db_editor/widgets/graph_view_mixin.py", line 294, in _handle_tree_selection_changed
    self.build_graph()
  File "/home/manuel/Codes/spine/Spine-Toolbox/spinetoolbox/spine_db_editor/widgets/graph_view_mixin.py", line 319, in build_graph
    self.layout_gens[self._layout_gen_id] = layout_gen = self._make_layout_generator()
  File "/home/manuel/Codes/spine/Spine-Toolbox/spinetoolbox/spine_db_editor/widgets/graph_view_mixin.py", line 522, in _make_layout_generator
    return GraphLayoutGeneratorRunnable(
  File "/home/manuel/Codes/spine/Spine-Toolbox/spinetoolbox/spine_db_editor/widgets/graph_layout_generator.py", line 122, in __init__
    QRunnable.__init__(self)
TypeError: __init__() missing 1 required positional argument: 'vertex_count'
```

**Comment by PekkaSavolainen** [comment]
This is probably related.

https://bugreports.qt.io/projects/PYSIDE/issues/PYSIDE-2294?filter=allopenissues&orderby=created+DESC%2C+priority+DESC%2C+updated+DESC

**Comment by manuelma** [comment]
Yes!
I think PySide6 6.5.0 does it 'right' but if we fixed it for it we would probably break it for 6.4.x and below. So I think the fix is to use composition rather than inheritance which should work in all versions. I am giving it a try now

**Comment by PekkaSavolainen** [comment]
> I think PySide6 6.5.0 does it 'right' but if we fixed it for it we would probably break it for 6.4.x and below.

I think you are right. I guess the 'correct' way to do it would be to drop 6.4 support but we don't want to do it yet, at least not until 0.7 is out. Thanks for looking into PySide6 6.5 support because it looks like there are a lot of interesting features coming up in the pyside development pipeline (better async support, android support, WebEngine stuff, etc.).
