### ISSUE TITLE
IndexError in Importer specification editor

### ISSUE THREAD

**Issue by sjvrijn** [spine-tools/Spine-Toolbox#2119]
Steps to reproduce:
1. Open spinetoolbox from terminal
2. Drag new importer into view
3. Double click to edit specification
4. Select any connector
5. Rename bottom entry in 'Source Table' list to add an entry
6. Select the 'rename this to add table' again
7. Observe IndexError in terminal

```python
TypeError: print_exception(): Exception expected for value, str found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\src\Spine-Toolbox\src\spine-items\spine_items\importer\widgets\import_mappings.py", line 171, in _change_flattened_mappings
    if not current.isValid():
  File "C:\src\Spine-Toolbox\src\spine-items\spine_items\importer\mvcmodels\mappings_model.py", line 410, in parent
    index_item = index.internalPointer()
  File "C:\src\Spine-Toolbox\src\spine-items\spine_items\importer\mvcmodels\mappings_model.py", line 410, in parent
    index_item = index.internalPointer()
  File "C:\src\Spine-Toolbox\src\spine-items\spine_items\importer\mvcmodels\mappings_model.py", line 410, in parent
    index_item = index.internalPointer()
  [Previous line repeated 1 more time]
  File "C:\src\Spine-Toolbox\src\spine-items\spine_items\importer\mvcmodels\mappings_model.py", line 372, in index
    return self.createIndex(row, 0, parent_item.mapping_list[row])
IndexError: list index out of range
```

**Comment by jkiviluo** [comment]
Does not reproduce on my laptop. @sjvrijn can this be closed?
