### ISSUE TITLE
Toolbox crashing when deleting entity_classes (or entities)

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#2289]
Toolbox (v0.8-dev) crashes semi-regularly when trying to delete entity_classes. Usually no traceback. I got this on the last try (not necessarily related):

```
DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="MS Sans Serif", pointsize=12, pixelsize=16, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("MS Sans Serif", lfWidth=0, lfHeight=-16) dpi=96
Traceback (most recent call last):
  File "C:\data\SpineToolbox-entity\spinetoolbox\mvcmodels\minimal_tree_model.py", line 342, in data
    return item.data(index.column(), role)
  File "C:\data\SpineToolbox-entity\spinetoolbox\spine_db_editor\mvcmodels\entity_tree_item.py", line 89, in data
    return super().data(column, role)
  File "C:\data\SpineToolbox-entity\spinetoolbox\spine_db_editor\mvcmodels\multi_db_tree_item.py", line 465, in data
    return self.display_icon
  File "C:\data\SpineToolbox-entity\spinetoolbox\spine_db_editor\mvcmodels\entity_tree_item.py", line 60, in display_icon
    return self.db_mngr.entity_class_icon(self.first_db_map, self.db_map_id(self.first_db_map))
  File "C:\data\SpineToolbox-entity\spinetoolbox\spine_db_editor\mvcmodels\multi_db_tree_item.py", line 130, in first_db_map
    return list(self._db_map_ids.keys())[0]
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\data\SpineToolbox-entity\spinetoolbox\spine_db_editor\widgets\item_metadata_editor.py", line 65, in _reload_entity_metadata
    self._item_metadata_table_view.setEnabled(False)
SystemError: <PySide6.QtCore.MetaFunction object at 0x000002B8FEAFFF70> returned a result with an error set
Traceback (most recent call last):
  File "C:\data\SpineToolbox-entity\spinetoolbox\mvcmodels\minimal_tree_model.py", line 342, in data
    return item.data(index.column(), role)
  File "C:\data\SpineToolbox-entity\spinetoolbox\spine_db_editor\mvcmodels\entity_tree_item.py", line 89, in data
    return super().data(column, role)
  File "C:\data\SpineToolbox-entity\spinetoolbox\spine_db_editor\mvcmodels\multi_db_tree_item.py", line 465, in data
    return self.display_icon
  File "C:\data\SpineToolbox-entity\spinetoolbox\spine_db_editor\mvcmodels\entity_tree_item.py", line 60, in display_icon
    return self.db_mngr.entity_class_icon(self.first_db_map, self.db_map_id(self.first_db_map))
  File "C:\data\SpineToolbox-entity\spinetoolbox\spine_db_editor\mvcmodels\multi_db_tree_item.py", line 130, in first_db_map
    return list(self._db_map_ids.keys())[0]
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\data\SpineToolbox-entity\spinetoolbox\spine_db_editor\widgets\item_metadata_editor.py", line 65, in _reload_entity_metadata
    self._item_metadata_table_view.setEnabled(False)
SystemError: <PySide6.QtCore.MetaFunction object at 0x000002B8FEAFFF70> returned a result with an error set
```

**Comment by jkiviluo** [comment]
Seems to happen if I remove more than one entity_class at once or if I remove an entity class that has dependent entity_classes.

**Comment by soininen** [comment]
I ran into this issue while fixing unit tests under #2294.

**Comment by soininen** [comment]
The above commit hopefully fixes this.
