### ISSUE TITLE
Closing Database editor without committing changes gives Traceback

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2291]
- Create a new database
- Add an entity class
- Close the editor discarding changes

```
Traceback (most recent call last):
  File "spinetoolbox\helpers.py", line 122, in new_function
    return func(*args, **kwargs)
  File "spinetoolbox\fetch_parent.py", line 99, in _apply_pending_changes
    self.handle_items_removed({db_map: data})
  File "spinetoolbox\fetch_parent.py", line 297, in handle_items_removed
    self._handle_items_removed(db_map_data)
  File "spinetoolbox\spine_db_editor\mvcmodels\multi_db_tree_item.py", line 302, in handle_items_removed
    db_map_ids = {db_map: {x["id"] for x in data} for db_map, data in db_map_data.items()}
  File "spinetoolbox\spine_db_editor\mvcmodels\multi_db_tree_item.py", line 302, in <dictcomp>
    db_map_ids = {db_map: {x["id"] for x in data} for db_map, data in db_map_data.items()}
  File "spinetoolbox\spine_db_editor\mvcmodels\multi_db_tree_item.py", line 302, in <setcomp>
    db_map_ids = {db_map: {x["id"] for x in data} for db_map, data in db_map_data.items()}
  File "spinedb_api\db_cache_base.py", line 840, in __getitem__
    return super().__getitem__(key)
  File "spinedb_api\temp_id.py", line 57, in __getitem__
    return super().__getitem__(key)
KeyError: 'id'
```

**Comment by PiispaH** [comment]
Very similar Traceback also when pasting a row into db editor and closing it without committing:

```
Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox\helpers.py", line 122, in new_function
    return func(*args, **kwargs)
  File "C:\spine-toolbox\spinetoolbox\fetch_parent.py", line 99, in _apply_pending_changes
    self.handle_items_removed({db_map: data})
  File "C:\spine-toolbox\spinetoolbox\fetch_parent.py", line 297, in handle_items_removed
    self._handle_items_removed(db_map_data)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\compound_models.py", line 381, in handle_items_removed
    removed_ids = [x["id"] for x in items_per_class.get(model.entity_class_id, {})]
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\compound_models.py", line 381, in <listcomp>
    removed_ids = [x["id"] for x in items_per_class.get(model.entity_class_id, {})]
  File "C:\toolbox\src\spinedb-api\spinedb_api\db_cache_impl.py", line 326, in __getitem__
    return super().__getitem__(key)
  File "C:\toolbox\src\spinedb-api\spinedb_api\db_cache_impl.py", line 185, in __getitem__
    return super().__getitem__(key)
  File "C:\toolbox\src\spinedb-api\spinedb_api\db_cache_base.py", line 842, in __getitem__
    return super().__getitem__(key)
  File "C:\toolbox\src\spinedb-api\spinedb_api\temp_id.py", line 57, in __getitem__
    return super().__getitem__(key)
KeyError: 'id'
```

**Comment by soininen** [comment]
Should be fixed now.
