### ISSUE TITLE
DB editor item doesn't come back and causes a Traceback after commit and redo

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2325]
1. Open a fresh DB in DB editor
2. Add a scenario
3. Commit
4. Undo - The scenario is removed as it is supposed to
5. Commit
6. Redo - The deleted scenario doesn't come back like it should and the following Traceback springs up:

```
Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox\spine_db_commands.py", line 115, in redo
    self.db_mngr.do_restore_items(self.db_map, self.item_type, self.undo_ids)
  File "C:\spine-toolbox\spinetoolbox\helpers.py", line 122, in new_function
    return func(*args, **kwargs)
  File "C:\spine-toolbox\spinetoolbox\spine_db_manager.py", line 1277, in do_restore_items
    return worker.restore_items(item_type, ids)
  File "C:\spine-toolbox\spinetoolbox\helpers.py", line 122, in new_function
    return func(*args, **kwargs)
  File "C:\spine-toolbox\spinetoolbox\spine_db_worker.py", line 309, in restore_items
    items = self._db_map.restore_items(item_type, *ids)
  File "C:\toolbox\src\spinedb-api\spinedb_api\db_mapping_remove_mixin.py", line 47, in restore_items
    return [table_cache.restore_item(id_) for id_ in ids]
  File "C:\toolbox\src\spinedb-api\spinedb_api\db_mapping_remove_mixin.py", line 47, in <listcomp>
    return [table_cache.restore_item(id_) for id_ in ids]
  File "C:\toolbox\src\spinedb-api\spinedb_api\db_cache_base.py", line 424, in restore_item
    current_item.cascade_restore()
  File "C:\toolbox\src\spinedb-api\spinedb_api\db_cache_base.py", line 774, in cascade_restore
    raise RuntimeError("invalid status for item being restored")
RuntimeError: invalid status for item being restored
```

**Comment by manuelma** [comment]
Nice one @PiispaH - that RunTimeError is ours... I guess I missed a case in my analysis.
