### ISSUE TITLE
Upgrading DB fails

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#2338]
Trying to upgrade an existing DB fails in v0.8. The traceback is:

```
Traceback (most recent call last):
  File "C:\data\spi-entity2\spinetoolbox\spine_db_manager.py", line 330, in get_db_map
    return self._do_get_db_map(url, codename, create, upgrade)
  File "C:\data\spi-entity2\spinetoolbox\helpers.py", line 122, in new_function
    return func(*args, **kwargs)
  File "C:\data\spi-entity2\spinetoolbox\spine_db_manager.py", line 385, in _do_get_db_map
    raise error
  File "C:\data\spi-entity2\spinetoolbox\spine_db_manager.py", line 382, in _do_get_db_map
    db_map = worker.get_db_map(codename=codename, upgrade=upgrade, create=create)
  File "C:\data\spi-entity2\spinetoolbox\spine_db_worker.py", line 52, in get_db_map
    self._db_map = DatabaseMapping(self._db_url, *args, sqlite_timeout=2, chunk_size=_CHUNK_SIZE, **kwargs)
  File "C:\Users\prokjt\Miniconda3\envs\spi-entity2\lib\site-packages\spinedb_api\db_mapping.py", line 40, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\prokjt\Miniconda3\envs\spi-entity2\lib\site-packages\spinedb_api\db_mapping_base.py", line 113, in __init__
    self._original_engine = self.create_engine(
  File "C:\Users\prokjt\Miniconda3\envs\spi-entity2\lib\site-packages\spinedb_api\db_mapping_base.py", line 279, in create_engine
    raise SpineDBVersionError(url=sa_url, current=current, expected=head)
spinedb_api.exception.SpineDBVersionError: The database at 'sqlite:///C:\data\Toolbox_projects\NordicH2\generic_energy_data_specification.sqlite' is not the expected version.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\prokjt\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\prokjt\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table entity_alternative already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\data\spi-entity2\spinetoolbox\widgets\custom_qgraphicsscene.py", line 246, in event
    return super().event(event)
  File "C:\data\spi-entity2\src\spine-items\spine_items\data_store\data_store_icon.py", line 39, in mouseDoubleClickEvent
    item.project_item.open_url_in_spine_db_editor()
  File "C:\data\spi-entity2\src\spine-items\spine_items\data_store\data_store.py", line 291, in open_url_in_spine_db_editor
    self._toolbox.db_mngr.open_db_editor(db_url_codenames)
  File "C:\data\spi-entity2\spinetoolbox\spine_db_manager.py", line 1514, in open_db_editor
    multi_db_editor = MultiSpineDBEditor(self, db_url_codenames)
  File "C:\data\spi-entity2\spinetoolbox\spine_db_editor\widgets\multi_spine_db_editor.py", line 48, in __init__
    self.add_new_tab(db_url_codenames)
  File "C:\data\spi-entity2\spinetoolbox\widgets\multi_tab_window.py", line 131, in add_new_tab
    tab = self._make_new_tab(*args, **kwargs)
  File "C:\data\spi-entity2\spinetoolbox\spine_db_editor\widgets\multi_spine_db_editor.py", line 90, in _make_new_tab
    tab.load_db_urls(db_url_codenames, create=True)
  File "C:\data\spi-entity2\spinetoolbox\spine_db_editor\widgets\spine_db_editor.py", line 166, in load_db_urls
    db_map = self.db_mngr.get_db_map(url, self, codename=codename, create=create)
  File "C:\data\spi-entity2\spinetoolbox\spine_db_manager.py", line 346, in get_db_map
    return self.get_db_map(url, logger, codename=codename, create=create, upgrade=True)
  File "C:\data\spi-entity2\spinetoolbox\spine_db_manager.py", line 330, in get_db_map
    return self._do_get_db_map(url, codename, create, upgrade)
  File "C:\data\spi-entity2\spinetoolbox\helpers.py", line 122, in new_function
    return func(*args, **kwargs)
  File "C:\data\spi-entity2\spinetoolbox\spine_db_manager.py", line 385, in _do_get_db_map
    raise error
  File "C:\data\spi-entity2\spinetoolbox\spine_db_manager.py", line 382, in _do_get_db_map
    db_map = worker.get_db_map(codename=codename, upgrade=upgrade, create=create)
  File "C:\data\spi-entity2\spinetoolbox\spine_db_worker.py", line 52, in get_db_map
    self._db_map = DatabaseMapping(self._db_url, *args, sqlite_timeout=2, chunk_size=_CHUNK_SIZE, **kwargs)
  File "C:\Users\prokjt\Miniconda3\envs\spi-entity2\lib\site-packages\spinedb_api\db_mapping.py", line 40, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\prokjt\Miniconda3\envs\spi-entity2\lib\site-packages\spinedb_api\db_mapping_base.py", line 113, in __init__
    self._original_engine = self.create_engine(
  File "C:\Users\prokjt\Miniconda3\envs\spi-entity2\lib\site-packages\spinedb_api\db_mapping_base.py", line 296, in create_engine
    environment_context.run_migrations()
  File "C:\Users\prokjt\AppData\Roaming\Python\Python39\site-packages\alembic\runtime\environment.py", line 851, in run_migrations
    self.get_context().run_migrations(**kw)
  File "C:\Users\prokjt\AppData\Roaming\Python\Python39\site-packages\alembic\runtime\migration.py", line 620, in run_migrations
    step.migration_fn(**kw)
  File "C:\Users\prokjt\Miniconda3\envs\spi-entity2\lib\site-packages\spinedb_api\alembic\versions\ce9faa82ed59_create_entity_alternative_table.py", line 21, in upgrade
    op.create_table(
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "C:\Users\prokjt\AppData\Roaming\Python\Python39\site-packages\alembic\operations\ops.py", line 1254, in create_table
    return operations.invoke(op)
  File "C:\Users\prokjt\AppData\Roaming\Python\Python39\site-packages\alembic\operations\base.py", line 392, in invoke
    return fn(self, operation)
  File "C:\Users\prokjt\AppData\Roaming\Python\Python39\site-packages\alembic\operations\toimpl.py", line 114, in create_table
    operations.impl.create_table(table)
  File "C:\Users\prokjt\AppData\Roaming\Python\Python39\site-packages\alembic\ddl\impl.py", line 356, in create_table
    self._exec(schema.CreateTable(table))
  File "C:\Users\prokjt\AppData\Roaming\Python\Python39\site-packages\alembic\ddl\impl.py", line 197, in _exec
    return conn.execute(construct, multiparams)
  File "C:\Users\prokjt\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "C:\Users\prokjt\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\sql\ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "C:\Users\prokjt\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "C:\Users\prokjt\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\prokjt\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\prokjt\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Users\prokjt\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\prokjt\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table entity_alternative already exists
[SQL:
CREATE TABLE entity_alternative (
        id INTEGER NOT NULL,
        entity_id INTEGER NOT NULL,
        alternative_id INTEGER NOT NULL,
        active BOOLEAN DEFAULT 1 NOT NULL,
        commit_id INTEGER,
        CONSTRAINT pk_entity_alternative PRIMARY KEY (id),
        CONSTRAINT fk_entity_alternative_alternative_id_alternative FOREIGN KEY(alternative_id) REFERENCES alternative (id) ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT fk_entity_alternative_commit_id_commit FOREIGN KEY(commit_id) REFERENCES "commit" (id),
        CONSTRAINT fk_entity_alternative_entity_id_entity FOREIGN KEY(entity_id) REFERENCES entity (id) ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT uq_entity_alternative_entity_idalternative_id UNIQUE (entity_id, alternative_id),
        CONSTRAINT ck_entity_alternative_active CHECK (active IN (0, 1))
)

]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by manuelma** [comment]
I think the problem is that at some point, creating a new spine db would create the entity_alternative table but set the wrong version in the alembic table. The work-around would be to manually modify the version using an external DB browser.

This is not something we should try and fix in my opinion.

**Comment by jkiviluo** [comment]
To what I should update the version? I was trying to see how the versions change, but it's really hairy in the src\spinedb-api\spinedb_api\alembic\versions directory. Also, there may be a loop: 6b7c994c1c61_drop_object_and_relationship_tables.py is pointing to future revision as 'down_revision' (or 'Revises').

**Comment by jkiviluo** [comment]
All right, I had to update the version to ce9faa82ed59 (seems like the latest) and then the old DB started working, which is a relief.

**Comment by manuelma** [comment]
Good job! Sorry I didn't reply earlier. I guess a simpler way to find the current version is to create a new DB and look at the value in the alembic table.
