### ISSUE TITLE
Traceback when switching to Graph view in Database editor

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2358]
Steps to reproduce:
1. Add entity class A and entity a
2. Add entity class B and entity b
3. Add entity class with dimensions A, B and entity a, b
4. Switch to Graph view or, if already in Graph view, to Table view and back

```
Traceback (most recent call last):
  File "spinetoolbox\helpers.py", line 122, in new_function
    return func(*args, **kwargs)
  File "spinetoolbox\fetch_parent.py", line 93, in _apply_pending_changes
    self.handle_items_added({db_map: data})
  File "spinetoolbox\fetch_parent.py", line 327, in handle_items_added
    self._handle_items_added(db_map_data)
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 998, in _handle_alternatives_added
    self.add_to_model(data)
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 461, in add_to_model
    row_count, column_count = self.model.add_to_model(db_map_data)
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_model.py", line 89, in add_to_model
    self._column_data_header = self._get_unique_index_values(self.pivot_columns)
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_model.py", line 169, in _get_unique_index_values
    return sorted(
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_model.py", line 171, in <lambda>
    key=lambda x: tuple(
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_model.py", line 172, in <genexpr>
    self.top_left_headers[header_name].header_data(header_id) for header_name, header_id in zip(indexes, x)
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 150, in header_data
    return self._get_header_data_from_db("parameter_definition", header_id, "name", role)
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 59, in _get_header_data_from_db
    return item.get(field_name)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by jkiviluo** [comment]
Thanks, I've stumbled on something like this many times today.

**Comment by soininen** [comment]
Cannot reproduce this anymore. Seems like it has been fixed already.
