### ISSUE TITLE
Selecting recently added entity class while in Pivot view gives Traceback

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2386]
Starting with an empty database and while in Pivot view (Value):
1. Add entity class from Entity tree's context menu
2. Select the entity from the tree

```
Traceback (most recent call last):
  File "spinetoolbox\helpers.py", line 122, in new_function
    return func(*args, **kwargs)
  File "spinetoolbox\fetch_parent.py", line 95, in _apply_pending_changes
    self.handle_items_added({db_map: data})
  File "spinetoolbox\fetch_parent.py", line 329, in handle_items_added
    self._handle_items_added(db_map_data)
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 995, in _handle_alternatives_added
    self.add_to_model(data)
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 461, in add_to_model
    row_count, column_count = self.model.add_to_model(db_map_data)
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_model.py", line 88, in add_to_model
    self._row_data_header = self._get_unique_index_values(self.pivot_rows)
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_model.py", line 169, in _get_unique_index_values
    return sorted(
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_model.py", line 171, in <lambda>
    key=lambda x: tuple(
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_model.py", line 172, in <genexpr>
    self.top_left_headers[header_name].header_data(header_id) for header_name, header_id in zip(indexes, x)
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 118, in header_data
    return self._get_header_data_from_db("entity", header_id, "name", role)
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 57, in _get_header_data_from_db
    item = self.db_mngr.get_item(db_map, item_type, id_)
  File "spinetoolbox\spine_db_manager.py", line 673, in get_item
    return db_map.get_item(item_type, id=id_)
  File "spinedb_api\db_mapping.py", line 396, in get_item
    item = self.mapped_table(item_type).find_item(kwargs, fetch=fetch)
  File "spinedb_api\db_mapping_base.py", line 383, in find_item
    return self._find_item_by_unique_key(item, skip_keys=skip_keys, fetch=fetch)
  File "spinedb_api\db_mapping_base.py", line 407, in _find_item_by_unique_key
    error = mapped_item.polish()
  File "spinedb_api\mapped_items.py", line 167, in polish
    base_name = self["class_name"] + "_" + "__".join(self["element_name_list"])
  File "spinedb_api\mapped_items.py", line 133, in __getitem__
    return super().__getitem__(key)
  File "spinedb_api\db_mapping_base.py", line 999, in __getitem__
    ref_id = self[src_key]
  File "spinedb_api\mapped_items.py", line 133, in __getitem__
    return super().__getitem__(key)
  File "spinedb_api\db_mapping_base.py", line 1003, in __getitem__
    return super().__getitem__(key)
KeyError: 'class_id'
```

**Comment by soininen** [comment]
Looks like I broke something else while fixing this...
