### ISSUE TITLE
Purging entity class gives Traceback

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2393]
In Database editor:
1. Start with an empty database
2. Add an entity class
3. Purge all data from the hamburger menu

```
Traceback (most recent call last):
  File "spinetoolbox\helpers.py", line 122, in new_function
    return func(*args, **kwargs)
  File "spinetoolbox\fetch_parent.py", line 101, in _apply_pending_changes
    self.handle_items_removed({db_map: data})
  File "spinetoolbox\fetch_parent.py", line 334, in handle_items_removed
    self._handle_items_removed(db_map_data)
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 1014, in _handle_alternatives_removed
    data = self._load_empty_parameter_value_data(db_map_alternative_ids=db_map_alternative_ids)
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 1018, in _load_empty_parameter_value_data
    return self._parent.load_empty_parameter_value_data(*args, **kwargs)
  File "spinetoolbox\spine_db_editor\widgets\tabular_view_mixin.py", line 424, in load_empty_parameter_value_data
    db_map_entity_ids = {
  File "spinetoolbox\spine_db_editor\widgets\tabular_view_mixin.py", line 425, in <dictcomp>
    db_map: [tuple((db_map, None) for _ in self.current_dimension_id_list)] for db_map in self.db_maps
  File "spinetoolbox\spine_db_editor\widgets\tabular_view_mixin.py", line 172, in current_dimension_id_list
    current_dimension_id_list = [{} for _ in self.current_dimension_name_list]
  File "spinetoolbox\spine_db_editor\widgets\tabular_view_mixin.py", line 189, in current_dimension_name_list
    entity_class = self.first_current_entity_class
  File "spinetoolbox\spine_db_editor\widgets\tabular_view_mixin.py", line 184, in first_current_entity_class
    db_map, class_id = next(iter(self.current_class_id.items()))
StopIteration
```

**Comment by soininen** [comment]
I could not reproduce the exact Traceback here but stumbled upon other issues with Pivot tables that should be fixed now.
