### ISSUE TITLE
Changing parameter definition causes entity name to disappear.

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#2418]
- Make a new parameter_list with some values
- Make a new parameter definition:
- Add name
- Choose the parameter_list
- Watch how the name disappears
- (Can be added again)

May be related:
```
Traceback (most recent call last):
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\mvcmodels\compound_table_model.py", line 179, in data
    return self.map_to_sub(index).data(role)
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\spine_db_editor\mvcmodels\single_models.py", line 372, in data
    return self.db_mngr.get_value(self.db_map, self.item_type, id_, role)
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\spine_db_manager.py", line 797, in get_value
    list_value_id = id_ if item_type == "list_value" else item["list_value_id"]
  File "C:\data\spi-entity\Spine-Toolbox\src\spinedb-api\spinedb_api\db_mapping_base.py", line 1084, in __getitem__
    return self._mapped_item[key]
  File "C:\data\spi-entity\Spine-Toolbox\src\spinedb-api\spinedb_api\mapped_items.py", line 406, in __getitem__
    return super().__getitem__(key)
  File "C:\data\spi-entity\Spine-Toolbox\src\spinedb-api\spinedb_api\mapped_items.py", line 290, in __getitem__
    return super().__getitem__(key)
  File "C:\data\spi-entity\Spine-Toolbox\src\spinedb-api\spinedb_api\db_mapping_base.py", line 1038, in __getitem__
    return super().__getitem__(key)
KeyError: 'list_value_id'
```

**Comment by jkiviluo** [comment]
This is actually a wider bug. The entity name disappears also when I try to add a description.
