### ISSUE TITLE
Toolbox not opening because of imports

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2427]
Trying to open Toolbox caused the following Traceback and Toolbox wouldn't open because of this:

```
Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox.py", line 21, in <module>
    sys.exit(main())
  File "C:\spine-toolbox\spinetoolbox\main.py", line 65, in main
    window = ToolboxUI()
  File "C:\spine-toolbox\spinetoolbox\ui_main.py", line 214, in __init__
    self.parse_project_item_modules()
  File "C:\spine-toolbox\spinetoolbox\ui_main.py", line 391, in parse_project_item_modules
    self._item_categories, self.item_factories = load_project_items("spine_items")
  File "C:\spine-toolbox\spinetoolbox\load_project_items.py", line 46, in load_project_items
    module_material = _find_module_material(module)
  File "C:\spine-toolbox\spinetoolbox\load_project_items.py", line 60, in _find_module_material
    submodule = __import__(modname, fromlist="dummy")
  File "C:\toolbox\src\spine-items\spine_items\importer\executable_item.py", line 28, in <module>
    from spine_engine.project_item.project_item_resource import get_labelled_sources
ImportError: cannot import name 'get_labelled_sources' from 'spine_engine.project_item.project_item_resource' (C:\toolbox\src\spine-engine\spine_engine\project_item\project_item_resource.py)
```

**Comment by soininen** [comment]
Oops, looks like I merged spine-tools/spine-engine#119 too quickly.
