### ISSUE TITLE
Unable to open or upgrade a database

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2428]
I have a few databases that can't be opened anymore. When I try to open them, they prompt me to upgrade them. Then when I press the upgrade button only the Traceback pops up and nothing else happens.

```
Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox\spine_db_manager.py", line 331, in get_db_map
    return self._do_get_db_map(url, codename, create, upgrade)
  File "C:\spine-toolbox\spinetoolbox\helpers.py", line 122, in new_function
    return func(*args, **kwargs)
  File "C:\spine-toolbox\spinetoolbox\spine_db_manager.py", line 386, in _do_get_db_map
    raise error
  File "C:\spine-toolbox\spinetoolbox\spine_db_manager.py", line 383, in _do_get_db_map
    db_map = worker.get_db_map(codename=codename, upgrade=upgrade, create=create)
  File "C:\spine-toolbox\spinetoolbox\spine_db_worker.py", line 55, in get_db_map
    self._db_map = DatabaseMapping(self._db_url, *args, sqlite_timeout=2, **kwargs)
  File "C:\toolbox\src\spinedb-api\spinedb_api\db_mapping.py", line 163, in __init__
    self._original_engine = self.create_engine(
  File "C:\toolbox\src\spinedb-api\spinedb_api\db_mapping.py", line 261, in create_engine
    raise SpineDBVersionError(url=sa_url, current=current, expected=head)
spinedb_api.exception.SpineDBVersionError: The database at 'sqlite:///C:\Toolbox projects\cutting_edge\.spinetoolbox\items\replicate_2158\replicate_2158.sqlite' is not the expected version.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table entity_alternative already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox\widgets\custom_qgraphicsscene.py", line 246, in event
    return super().event(event)
  File "C:\toolbox\src\spine-items\spine_items\data_store\data_store_icon.py", line 39, in mouseDoubleClickEvent
    item.project_item.open_url_in_spine_db_editor()
  File "C:\toolbox\src\spine-items\spine_items\data_store\data_store.py", line 291, in open_url_in_spine_db_editor
    self._toolbox.db_mngr.open_db_editor(db_url_codenames)
  File "C:\spine-toolbox\spinetoolbox\spine_db_manager.py", line 1631, in open_db_editor
    multi_db_editor = MultiSpineDBEditor(self, db_url_codenames)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\widgets\multi_spine_db_editor.py", line 49, in __init__
    if not self.add_new_tab(db_url_codenames):
  File "C:\spine-toolbox\spinetoolbox\widgets\multi_tab_window.py", line 134, in add_new_tab
    tab = self._make_new_tab(*args, **kwargs)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\widgets\multi_spine_db_editor.py", line 93, in _make_new_tab
    if not tab.load_db_urls(db_url_codenames, create=True):
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\widgets\spine_db_editor.py", line 166, in load_db_urls
    db_map = self.db_mngr.get_db_map(url, self, codename=codename, create=create)
  File "C:\spine-toolbox\spinetoolbox\spine_db_manager.py", line 347, in get_db_map
    return self.get_db_map(url, logger, codename=codename, create=create, upgrade=True)
  File "C:\spine-toolbox\spinetoolbox\spine_db_manager.py", line 331, in get_db_map
    return self._do_get_db_map(url, codename, create, upgrade)
  File "C:\spine-toolbox\spinetoolbox\helpers.py", line 122, in new_function
    return func(*args, **kwargs)
  File "C:\spine-toolbox\spinetoolbox\spine_db_manager.py", line 386, in _do_get_db_map
    raise error
  File "C:\spine-toolbox\spinetoolbox\spine_db_manager.py", line 383, in _do_get_db_map
    db_map = worker.get_db_map(codename=codename, upgrade=upgrade, create=create)
  File "C:\spine-toolbox\spinetoolbox\spine_db_worker.py", line 55, in get_db_map
    self._db_map = DatabaseMapping(self._db_url, *args, sqlite_timeout=2, **kwargs)
  File "C:\toolbox\src\spinedb-api\spinedb_api\db_mapping.py", line 163, in __init__
    self._original_engine = self.create_engine(
  File "C:\toolbox\src\spinedb-api\spinedb_api\db_mapping.py", line 278, in create_engine
    environment_context.run_migrations()
  File "C:\toolbox\lib\site-packages\alembic\runtime\environment.py", line 868, in run_migrations
    self.get_context().run_migrations(**kw)
  File "C:\toolbox\lib\site-packages\alembic\runtime\migration.py", line 622, in run_migrations
    step.migration_fn(**kw)
  File "C:\toolbox\src\spinedb-api\spinedb_api\alembic\versions\ce9faa82ed59_create_entity_alternative_table.py", line 21, in upgrade
    op.create_table(
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "C:\toolbox\lib\site-packages\alembic\operations\ops.py", line 1255, in create_table
    return operations.invoke(op)
  File "C:\toolbox\lib\site-packages\alembic\operations\base.py", line 401, in invoke
    return fn(self, operation)
  File "C:\toolbox\lib\site-packages\alembic\operations\toimpl.py", line 114, in create_table
    operations.impl.create_table(table)
  File "C:\toolbox\lib\site-packages\alembic\ddl\impl.py", line 354, in create_table
    self._exec(schema.CreateTable(table))
  File "C:\toolbox\lib\site-packages\alembic\ddl\impl.py", line 193, in _exec
    return conn.execute(  # type: ignore[call-overload]
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "C:\toolbox\lib\site-packages\sqlalchemy\sql\ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "C:\toolbox\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table entity_alternative already exists
[SQL: 
CREATE TABLE entity_alternative (
	id INTEGER NOT NULL, 
	entity_id INTEGER NOT NULL, 
	alternative_id INTEGER NOT NULL, 
	active BOOLEAN DEFAULT 1 NOT NULL, 
	commit_id INTEGER, 
	CONSTRAINT pk_entity_alternative PRIMARY KEY (id), 
	CONSTRAINT fk_entity_alternative_alternative_id_alternative FOREIGN KEY(alternative_id) REFERENCES alternative (id) ON DELETE CASCADE ON UPDATE CASCADE, 
	CONSTRAINT fk_entity_alternative_commit_id_commit FOREIGN KEY(commit_id) REFERENCES "commit" (id), 
	CONSTRAINT fk_entity_alternative_entity_id_entity FOREIGN KEY(entity_id) REFERENCES entity (id) ON DELETE CASCADE ON UPDATE CASCADE, 
	CONSTRAINT uq_entity_alternative_entity_idalternative_id UNIQUE (entity_id, alternative_id), 
	CONSTRAINT ck_entity_alternative_active CHECK (active IN (0, 1))
)

]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by manuelma** [comment]
This is my fault. I introduced the entity_alternative table without the corresponding migration script which means that new spine dbs created duiring that period cannot be upgraded automatically. This is now fixed and won't affect future users.

The workaround for users caught by this is to change the alembic version number in your DB to ce9faa82ed59 (which you can do with an external DB editor) and then open the DB with the Spine DB editor.

**Comment by PiispaH** [comment]
Aah okay, good to know 👍. I will then close this issue.
