### ISSUE TITLE
Adding new parameter definition fails in v0.8

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#2432]
When trying to add new paremeter definition, I get this:

```
(spi-entity) C:\data\spi-entity\Spine-Toolbox>python spinetoolbox.py
Traceback (most recent call last):
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\widgets\notification.py", line 221, in _push_notification
    if self._settings.value(self._settings_key, defaultValue="2") != "2":
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\spine_db_commands.py", line 119, in redo
    data = self.db_mngr.do_add_items(self.db_map, self.item_type, self.redo_data, check=self._check)
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\helpers.py", line 122, in new_function
    return func(*args, **kwargs)
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\spine_db_manager.py", line 1337, in do_add_items
    return worker.add_items(item_type, data, check)
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\helpers.py", line 122, in new_function
    return func(*args, **kwargs)
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\spine_db_worker.py", line 203, in add_items
    items, errors = self._db_map.add_items(item_type, *orig_items, check=check)
  File "C:\data\spi-entity\Spine-Toolbox\src\spinedb-api\spinedb_api\db_mapping.py", line 424, in add_items
    item, error = self.add_item(item_type, check, **item)
  File "C:\data\spi-entity\Spine-Toolbox\src\spinedb-api\spinedb_api\db_mapping.py", line 406, in add_item
    checked_item, error = mapped_table.checked_item_and_error(kwargs)
  File "C:\data\spi-entity\Spine-Toolbox\src\spinedb-api\spinedb_api\db_mapping_base.py", line 420, in checked_item_and_error
    self.check_fields(candidate_item._asdict())
  File "C:\data\spi-entity\Spine-Toolbox\src\spinedb-api\spinedb_api\db_mapping_base.py", line 530, in check_fields
    raise SpineDBAPIError("\n".join(errors))
spinedb_api.exception.SpineDBAPIError: invalid keyword argument 'row' for 'parameter_definition' - valid arguments are entity_class_name, name, default_value, default_type, parameter_value_list_name, description.
```

**Comment by manuelma** [comment]
Oops, I missed that. Thank you for this, will fix.

**Comment by manuelma** [comment]
It might work better now, please reopen if not.

**Comment by jkiviluo** [comment]
Yes, it works now. I tried to see what's the problem is myself, but the traceback didn't get me anywhere near the source of the problem. Lot to learn...
