### ISSUE TITLE
Cannot choose default value for parameters in DB editor v0.8

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#2443]
As per title. Switch to parameter definition, try to choose a default for a parameter definition. Getting this in console:
```
AttributeError: Slot 'ChangeNotifier::_push_notification(int)' not found.
```

And after pulling the latest I got this:
```
Traceback (most recent call last):
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\widgets\notification.py", line 221, in _push_notification
    if self._settings.value(self._settings_key, defaultValue="2") != "2":
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\spine_db_commands.py", line 154, in redo
    for x in self.db_mngr.do_update_items(self.db_map, self.item_type, self.redo_data, check=self._check)
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\helpers.py", line 122, in new_function
    return func(*args, **kwargs)
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\spine_db_manager.py", line 1360, in do_update_items
    return worker.update_items(item_type, data, check)
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\helpers.py", line 122, in new_function
    return func(*args, **kwargs)
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\spine_db_worker.py", line 227, in update_items
    items, errors = self._db_map.update_items(item_type, *orig_items, check=check)
  File "C:\data\spi-entity\Spine-Toolbox\src\spinedb-api\spinedb_api\db_mapping.py", line 477, in update_items
    return self._modify_items(lambda x: self.update_item(item_type, check=check, **x), *items, strict=strict)
  File "C:\data\spi-entity\Spine-Toolbox\src\spinedb-api\spinedb_api\db_mapping.py", line 389, in _modify_items
    item, error = function(item)
  File "C:\data\spi-entity\Spine-Toolbox\src\spinedb-api\spinedb_api\db_mapping.py", line 477, in <lambda>
    return self._modify_items(lambda x: self.update_item(item_type, check=check, **x), *items, strict=strict)
  File "C:\data\spi-entity\Spine-Toolbox\src\spinedb-api\spinedb_api\db_mapping.py", line 461, in update_item
    checked_item, error = mapped_table.checked_item_and_error(kwargs, for_update=True)
  File "C:\data\spi-entity\Spine-Toolbox\src\spinedb-api\spinedb_api\db_mapping_base.py", line 418, in checked_item_and_error
    self.check_fields(candidate_item._asdict())
  File "C:\data\spi-entity\Spine-Toolbox\src\spinedb-api\spinedb_api\db_mapping_base.py", line 529, in check_fields
    raise SpineDBAPIError("\n".join(errors))
spinedb_api.exception.SpineDBAPIError: invalid type for 'name' of 'parameter_definition' - got NoneType, expected str.
```

**Comment by jkiviluo** [comment]
Looks like it could be SpineDB_API issue.

**Comment by jkiviluo** [comment]
to be tested by @jkiviluo
