### ISSUE TITLE
hello_world_on_server execution test fails

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2478]
This happens on my system but not on GitHub actions. The test hangs forever with a Traceback:

```
Traceback (most recent call last):
  File "Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "spine-engine\spine_engine\server\remote_execution_service.py", line 95, in run
    converted_data = self.convert_input(engine_data, self.local_project_dir)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "spine-engine\spine_engine\server\remote_execution_service.py", line 201, in convert_input
    if specItemInfo["execution_settings"]["use_jupyter_console"]:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'use_jupyter_console'
```

**Comment by PekkaSavolainen** [comment]
I just noticed the same. You probably had the spineopt plugins installed and there's a 'run SpineOpt detached' spec which has an empty dict as it's execution_settings, which causes the traceback.
