### ISSUE TITLE
Execution tests are broken

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2480]
'RunSimpleImporterOnServer' execution test fails on `0.8-dev` branch with the following Traceback:

```
Exception in thread RemoteExecutionServiceThread:
Traceback (most recent call last):
  File "lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "spine-engine\spine_engine\server\remote_execution_service.py", line 137, in run
    self.push_socket.send_multipart([b"END", b""])
  File "lib\site-packages\zmq\sugar\socket.py", line 751, in send_multipart
    self.send(msg, zmq.SNDMORE | flags, copy=copy, track=track)
  File "lib\site-packages\zmq\sugar\socket.py", line 696, in send
    return super().send(data, flags=flags, copy=copy, track=track)
  File "zmq\\backend\\cython\\socket.pyx", line 742, in zmq.backend.cython.socket.Socket.send
  File "zmq\\backend\\cython\\socket.pyx", line 789, in zmq.backend.cython.socket.Socket.send
  File "zmq\\backend\\cython\\socket.pyx", line 255, in zmq.backend.cython.socket._send_copy
  File "zmq\\backend\\cython\\socket.pyx", line 250, in zmq.backend.cython.socket._send_copy
  File "zmq\\backend\\cython\\checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ContextTerminated: Context was terminated
sys:1: ResourceWarning: Unclosed socket <zmq.Socket(zmq.DEALER) at 0x2014bd851c0>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: Unclosed socket <zmq.Socket(zmq.PUSH) at 0x2014bd85a00>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by PekkaSavolainen** [comment]
Does this happen locally? I don't see it on my system.

**Comment by soininen** [comment]
> Does this happen locally? I don't see it on my system.

I can see it on my system.

**Comment by PekkaSavolainen** [comment]
Try restarting your IDE and/or close all shell windows (cmd.exe et al) that you may have used in running the server execution tests. There may be some zmq server processes lingering around.

**Comment by soininen** [comment]
The same error happens also in GitHub actions so it's not restricted to my system only.

**Comment by PekkaSavolainen** [comment]
I did some clean up work and the execution tests do pass now. See https://github.com/spine-tools/Spine-Toolbox/actions/runs/7476405898

**Comment by soininen** [comment]
Great! I guess we can then close this issue.

**Comment by soininen** [comment]
Actually, this was caused by some changes that I had in `spinedb_api` and the GitHub actions were failing due to a PR relying on the same changes. Now I need to figure out why seemingly unrelated database things could break remote execution...
