### ISSUE TITLE
Traceback in Index pivot view

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2481]
Just quickly recording a Traceback I came across while clicking random stuff in Index pivot view.

```
Traceback (most recent call last):
  File "spinetoolbox\spine_db_editor\widgets\stacked_view_mixin.py", line 188, in _handle_entity_tree_selection_changed_in_parameter_tables
    self._set_default_parameter_data(self.ui.treeView_entity.selectionModel().currentIndex())
  File "spinetoolbox\spine_db_editor\widgets\stacked_view_mixin.py", line 120, in _set_default_parameter_data
    default_db_map = item.first_db_map
  File "spinetoolbox\spine_db_editor\mvcmodels\multi_db_tree_item.py", line 135, in first_db_map
    return next(iter(self._db_map_ids))
StopIteration
```

**Comment by soininen** [comment]
I failed replicate the random clicking pattern needed to get the Traceback.
