### ISSUE TITLE
v0.8 Not able to add new entities for n-D classes

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#2484]
- Make a new data store
- Add a 0-d entity class
- Add couple of entities to the class
- Add another 1-d entity class, that is using the first entity_class as its dimension
- Try adding entities to this 1-d entity class
- Fails:

```
Traceback (most recent call last):
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\spine_db_editor\widgets\custom_delegates.py", line 775, in createEditor
    entity_name_list = self.parent().entity_name_list(index.row(), index.column())
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\spine_db_editor\widgets\manage_items_dialogs.py", line 260, in entity_name_list
    entities = self.db_map_ent_lookup[db_map]
  File "C:\Users\prokjt\Miniconda3\envs\spi-entity\lib\functools.py", line 993, in __get__
    val = self.func(instance)
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\spine_db_editor\widgets\manage_items_dialogs.py", line 225, in db_map_ent_lookup
    byname = DB_ITEM_SEPARATOR.join(x["byname"])
  File "C:\data\spi-entity\Spine-Toolbox\src\spinedb-api\spinedb_api\db_mapping_base.py", line 1126, in __getitem__
    return self._mapped_item[key]
  File "C:\data\spi-entity\Spine-Toolbox\src\spinedb-api\spinedb_api\mapped_items.py", line 173, in __getitem__
    return super().__getitem__(key)
  File "C:\data\spi-entity\Spine-Toolbox\src\spinedb-api\spinedb_api\db_mapping_base.py", line 1080, in __getitem__
    return super().__getitem__(key)
KeyError: 'byname'
```

**Comment by jkiviluo** [comment]
I had conflicting Toolbox and API versions.
