### ISSUE TITLE
Traceback when adding a second database to db editor

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2512]
When adding a database to db editor when the db already open in the editor is dirty, toolbox asks if to commit the changes. If the changes are commited, the second db won't be added and the following Traceback will pop up.

```
Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox\spine_db_manager.py", line 340, in get_db_map
    return self._do_get_db_map(url, codename, create, upgrade, window)
  File "C:\spine-toolbox\spinetoolbox\helpers.py", line 122, in new_function
    return func(*args, **kwargs)
  File "C:\spine-toolbox\spinetoolbox\spine_db_manager.py", line 398, in _do_get_db_map
    raise error
  File "C:\spine-toolbox\spinetoolbox\spine_db_manager.py", line 395, in _do_get_db_map
    db_map = worker.get_db_map(codename=codename, upgrade=upgrade, create=create)
  File "C:\spine-toolbox\spinetoolbox\spine_db_worker.py", line 55, in get_db_map
    self._db_map = DatabaseMapping(self._db_url, *args, sqlite_timeout=2, **kwargs)
  File "C:\toolbox\src\spinedb-api\spinedb_api\db_mapping.py", line 166, in __init__
    self._original_engine = self.create_engine(
  File "C:\toolbox\src\spinedb-api\spinedb_api\db_mapping.py", line 264, in create_engine
    raise SpineDBVersionError(url=sa_url, current=current, expected=head)
spinedb_api.exception.SpineDBVersionError: The database at 'sqlite:///C:\Toolbox projects\DS_dirty\.spinetoolbox\items\test\test.sqlite' is not the expected version.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1204, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\default.py", line 812, in _init_compiled
    self.compiled_parameters = [compiled.construct_params()]
  File "C:\toolbox\lib\site-packages\sqlalchemy\sql\compiler.py", line 753, in construct_params
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: A value is required for bind parameter 'target_id' (Background on this error at: http://sqlalche.me/e/13/cd3x)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox\widgets\custom_qgraphicsscene.py", line 246, in event
    return super().event(event)
  File "C:\toolbox\src\spine-items\spine_items\data_store\data_store_icon.py", line 39, in mouseDoubleClickEvent
    item.project_item.open_url_in_spine_db_editor()
  File "C:\toolbox\src\spine-items\spine_items\data_store\data_store.py", line 301, in open_url_in_spine_db_editor
    self._toolbox.db_mngr.open_db_editor(db_url_codenames)
  File "C:\spine-toolbox\spinetoolbox\spine_db_manager.py", line 1658, in open_db_editor
    multi_db_editor = MultiSpineDBEditor(self, db_url_codenames)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\widgets\multi_spine_db_editor.py", line 49, in __init__
    if not self.add_new_tab(db_url_codenames, window=True):
  File "C:\spine-toolbox\spinetoolbox\widgets\multi_tab_window.py", line 134, in add_new_tab
    tab = self._make_new_tab(*args, **kwargs)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\widgets\multi_spine_db_editor.py", line 93, in _make_new_tab
    if not tab.load_db_urls(db_url_codenames, create=True, window=window):
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\widgets\spine_db_editor.py", line 166, in load_db_urls
    db_map = self.db_mngr.get_db_map(url, self, codename=codename, create=create, window=window)
  File "C:\spine-toolbox\spinetoolbox\spine_db_manager.py", line 356, in get_db_map
    return self.get_db_map(url, logger, codename=codename, create=create, upgrade=True, window=window)
  File "C:\spine-toolbox\spinetoolbox\spine_db_manager.py", line 340, in get_db_map
    return self._do_get_db_map(url, codename, create, upgrade, window)
  File "C:\spine-toolbox\spinetoolbox\helpers.py", line 122, in new_function
    return func(*args, **kwargs)
  File "C:\spine-toolbox\spinetoolbox\spine_db_manager.py", line 398, in _do_get_db_map
    raise error
  File "C:\spine-toolbox\spinetoolbox\spine_db_manager.py", line 395, in _do_get_db_map
    db_map = worker.get_db_map(codename=codename, upgrade=upgrade, create=create)
  File "C:\spine-toolbox\spinetoolbox\spine_db_worker.py", line 55, in get_db_map
    self._db_map = DatabaseMapping(self._db_url, *args, sqlite_timeout=2, **kwargs)
  File "C:\toolbox\src\spinedb-api\spinedb_api\db_mapping.py", line 166, in __init__
    self._original_engine = self.create_engine(
  File "C:\toolbox\src\spinedb-api\spinedb_api\db_mapping.py", line 281, in create_engine
    environment_context.run_migrations()
  File "C:\toolbox\lib\site-packages\alembic\runtime\environment.py", line 868, in run_migrations
    self.get_context().run_migrations(**kw)
  File "C:\toolbox\lib\site-packages\alembic\runtime\migration.py", line 622, in run_migrations
    step.migration_fn(**kw)
  File "C:\toolbox\src\spinedb-api\spinedb_api\alembic\versions\8b0eff478bcb_add_active_by_default_to_entity_class.py", line 38, in upgrade
    conn.execute(update_statement, [{"target_id": class_id} for class_id in dimensional_class_ids])
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "C:\toolbox\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1206, in _execute_context
    self._handle_dbapi_exception(
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "C:\toolbox\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1204, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\default.py", line 812, in _init_compiled
    self.compiled_parameters = [compiled.construct_params()]
  File "C:\toolbox\lib\site-packages\sqlalchemy\sql\compiler.py", line 753, in construct_params
    raise exc.InvalidRequestError(
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'target_id'
[SQL: UPDATE entity_class SET active_by_default=? WHERE entity_class.id = ?]
(Background on this error at: http://sqlalche.me/e/13/cd3x)
```

**Comment by soininen** [comment]
The Traceback has now been fixed.

However if you got it, it means that the database migration was left unfinished and will not work unless `_alembic_tmp_entity_class` table has been deleted manually.
