### ISSUE TITLE
Traceback when applying URL filters

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2552]
Applying a scenario filter when I had one entity class selected and the value pivot view was active caused the following Traceback:

```
Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox\spine_db_worker.py", line 157, in <lambda>
    QTimer.singleShot(0, lambda parent=parent: self._do_fetch_more(parent))
  File "C:\spine-toolbox\spinetoolbox\spine_db_worker.py", line 138, in _do_fetch_more
    if self._iterate_mapping(parent) and not self._db_map.has_external_commits():
  File "C:\spine-toolbox\spinetoolbox\helpers.py", line 123, in new_function
    return func(*args, **kwargs)
  File "C:\spine-toolbox\spinetoolbox\spine_db_worker.py", line 101, in _iterate_mapping
    if index is not None or parent.accepts_item(item, self._db_map):
  File "C:\spine-toolbox\spinetoolbox\fetch_parent.py", line 340, in accepts_item
    return self._accepts_item(item, db_map)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\widgets\tabular_view_mixin.py", line 676, in <lambda>
    if self.first_current_entity_class["dimension_id_list"]
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\widgets\tabular_view_mixin.py", line 186, in first_current_entity_class
    db_map, class_id = next(iter(self.current_class_id.items()))
StopIteration
python-BaseException

Process finished with exit code -1073740791 (0xC0000409)
```

**Comment by PiispaH** [comment]
### Another way to get the same last few lines of the traceback:

From value pivot view, remove parameter definition by right click context menu, undo, refresh the database:

```
Traceback (most recent call last):
  File "C:\Users\hkhenrik\spine-toolbox\spinetoolbox\mvcmodels\filter_checkbox_list_model.py", line 307, in fetchMore
    self._db_mngr.fetch_more(db_map, self._fetch_parent)
  File "C:\Users\hkhenrik\spine-toolbox\spinetoolbox\spine_db_manager.py", line 211, in fetch_more
    worker.fetch_more(parent)
  File "C:\Users\hkhenrik\spine-toolbox\spinetoolbox\spine_db_worker.py", line 136, in fetch_more
    self._do_fetch_more(parent)
  File "C:\Users\hkhenrik\spine-toolbox\spinetoolbox\spine_db_worker.py", line 143, in _do_fetch_more
    if self._iterate_mapping(parent):
  File "C:\Users\hkhenrik\spine-toolbox\spinetoolbox\helpers.py", line 123, in new_function
    return func(*args, **kwargs)
  File "C:\Users\hkhenrik\spine-toolbox\spinetoolbox\spine_db_worker.py", line 102, in _iterate_mapping
    if index is not None or parent.accepts_item(item, self._db_map):
  File "C:\Users\hkhenrik\spine-toolbox\spinetoolbox\fetch_parent.py", line 340, in accepts_item
    return self._accepts_item(item, db_map)
  File "C:\Users\hkhenrik\spine-toolbox\spinetoolbox\spine_db_editor\widgets\tabular_view_mixin.py", line 676, in <lambda>
    if self.first_current_entity_class["dimension_id_list"]
  File "C:\Users\hkhenrik\spine-toolbox\spinetoolbox\spine_db_editor\widgets\tabular_view_mixin.py", line 186, in first_current_entity_class
    db_map, class_id = next(iter(self.current_class_id.items()))
StopIteration
```
