### ISSUE TITLE
Traceback when killing Julia console

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2558]
This Traceback appears when I kill a Julia console

```
Exception in thread Thread-77:
Traceback (most recent call last):
  File "lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "spine_engine\execution_managers\persistent_execution_manager.py", line 149, in _log_stdout
    for line in iter(self._persistent.stdout.readline, b''):
ValueError: PyMemoryView_FromBuffer(): info->buf must not be NULL
```

**Comment by PekkaSavolainen** [comment]
Happens when using a Microsoft Store Julia in Basic Console.

**Comment by PekkaSavolainen** [comment]
Should be fixed now.
