### ISSUE TITLE
Traceback when pressing edit on a entity in graph view context menu

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2564]
```
Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\widgets\custom_qgraphicsviews.py", line 397, in edit_selected
    self._spine_db_editor.show_edit_entities_form(ent_items)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\widgets\tree_view_mixin.py", line 160, in show_edit_entities_form
    dialog = EditEntitiesDialog(self, self.db_mngr, classed_items, class_key)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\widgets\edit_or_remove_items_dialogs.py", line 152, in __init__
    row_data = [DB_ITEM_SEPARATOR.join(byname) for byname in item.element_byname_list] + [data["name"]]
AttributeError: 'EntityItem' object has no attribute 'element_byname_list'
```

Also when pressing duplicate:
```
Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\graphics_items.py", line 606, in _duplicate
    self._spine_db_editor.duplicate_entity(self)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\widgets\spine_db_editor.py", line 602, in duplicate_entity
    class_name = entity_item.parent_item.name
AttributeError: 'EntityItem' object has no attribute 'parent_item'
```

**Comment by manuelma** [comment]
Should be fixed by https://github.com/spine-tools/Spine-Toolbox/commit/5cc9f232f06f9b20b52fabe228f48ff3c4c54478
