### ISSUE TITLE
Traceback from element -pivot view in 0.8-dev

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2571]
I had a 2-D entity class selected and the element pivot view open. Then I removed one entity by unchecking the box. When I tried to check the box again the following traceback popped up:

```
Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\widgets\tabular_view_mixin.py", line 796, in _add_values_to_frozen_table
    self.frozen_table_model.add_values(frozen_values)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\frozen_table_model.py", line 76, in add_values
    self._keep_sorted()
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\frozen_table_model.py", line 238, in _keep_sorted
    data = sorted(
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\frozen_table_model.py", line 240, in <lambda>
    key=lambda x: tuple(self._name_from_data(x[column], header[column]) for column in range(column_count)),
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\frozen_table_model.py", line 240, in <genexpr>
    key=lambda x: tuple(self._name_from_data(x[column], header[column]) for column in range(column_count)),
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\frozen_table_model.py", line 349, in _name_from_data
    return value.codename
AttributeError: 'tuple' object has no attribute 'codename'
```

**Comment by manuelma** [comment]
Does this still happen? Wasn't able to reproduce...

**Comment by PiispaH** [comment]
I can't reproduce this anymore either
