### ISSUE TITLE
Traceback from parameter value -table

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2574]
Got this traceback in 0.8-dev when defining a parameter value by filling in the alternative name last. Did many things different things before so not really sure how to reproduce.

````
Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox\helpers.py", line 123, in new_function
    return func(*args, **kwargs)
  File "C:\spine-toolbox\spinetoolbox\fetch_parent.py", line 102, in _apply_pending_changes
    last_handler({db_map: items})
  File "C:\spine-toolbox\spinetoolbox\fetch_parent.py", line 325, in handle_items_added
    self._handle_items_added(db_map_data)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 1026, in _handle_parameter_values_added
    self.add_to_model(data)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 479, in add_to_model
    frozen_values = self.model.frozen_values(db_map_data)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\pivot_model.py", line 115, in frozen_values
    frozen_getter = self._index_key_getter(self.pivot_frozen)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\pivot_model.py", line 151, in _index_key_getter
    return tuple_itemgetter(operator.itemgetter(*keys), len(keys))
TypeError: itemgetter expected 1 argument, got 0
```

**Comment by soininen** [comment]
I could reproduce the Traceback once, but encountered multiple others. They are now fixed and I did not see the one in the description either.
