### ISSUE TITLE
Traceback when adding entity class in db editor

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2575]
1. Have database with entity class A.
2. Purge everything except alternatives.
3. Commit
4. Add entity class B.
5. Commit -> B disappears.
7. Refresh ->B reappears.
8. Refresh again -> now there are two entity classes named B and Toolbox freezes

When trying to figure out how to reproduce this, one time also got this tracerback:

```
Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox\helpers.py", line 123, in new_function
    return func(*args, **kwargs)
  File "C:\spine-toolbox\spinetoolbox\fetch_parent.py", line 102, in _apply_pending_changes
    last_handler({db_map: items})
  File "C:\spine-toolbox\spinetoolbox\fetch_parent.py", line 325, in handle_items_added
    self._handle_items_added(db_map_data)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\multi_db_tree_item.py", line 329, in handle_items_added
    self.append_children_by_id(db_map_ids)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\multi_db_tree_item.py", line 349, in append_children_by_id
    self._merge_children(new_children)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\multi_db_tree_item.py", line 269, in _merge_children
    self._insert_children_sorted(new_children)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\multi_db_tree_item.py", line 291, in _insert_children_sorted
    for chunk, pos in bisect_chunks(self.children, new_children, key=self._children_sort_key):
  File "C:\spine-toolbox\spinetoolbox\helpers.py", line 1475, in bisect_chunks
    lo = bisect.bisect_left(current_data, key(item))
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

This might not be related to the issue but I got it by dong similar things: purging, committing, adding entity classes and refreshing the db.

**Comment by PiispaH** [comment]
Also managed to get two identical parameter values by adding it once and refreshing:

![image](https://github.com/spine-tools/Spine-Toolbox/assets/98282892/92048fbb-98a5-4fc7-8a84-d1ff48c04fd4)

**Comment by manuelma** [comment]
Are you on latests 0.8-dev @PiispaH ?

**Comment by PiispaH** [comment]
Yes, pulled the changes an hour ago @manuelma
