### ISSUE TITLE
Tracebacks when trying to add parameter values from value -pivot table in 0.8-dev

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2579]
Trying to add new parameter values from the value -pivot table either by opening the value editor or by typing straight causes the following tracebacks:

```
Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox\widgets\parameter_value_editor_base.py", line 106, in accept
    success = self._set_data(value)
  File "C:\spine-toolbox\spinetoolbox\widgets\parameter_value_editor.py", line 68, in _set_data
    self.set_data_delayed(value_type_tup)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 1277, in <lambda>
    {db_map: [func(db_map, header_ids, join_value_and_type(*value_type_tup))]}
TypeError: _entity_parameter_value_to_add() missing 1 required positional argument: 'ent_id_lookup'
```

```
Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\widgets\tabular_view_mixin.py", line 168, in _set_model_data
    self.pivot_table_proxy.setData(index, value)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 849, in setData
    return self.batch_set_data([index], [value])
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 865, in batch_set_data
    result = self._batch_set_inner_data(inner_data)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 887, in _batch_set_inner_data
    return self._do_batch_set_inner_data(row_map, column_map, data, values)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 1185, in _do_batch_set_inner_data
    return self._batch_set_parameter_value_data(row_map, column_map, data, values)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 1239, in _batch_set_parameter_value_data
    item = parameter_value_to_add(db_map, header_ids, values[row, column])
TypeError: _entity_parameter_value_to_add() missing 1 required positional argument: 'ent_id_lookup'
```

**Comment by manuelma** [comment]
Fixed by https://github.com/spine-tools/Spine-Toolbox/commit/1b2b2d1aa76faa6c96242828268888dd6b4cf888
