### ISSUE TITLE
Traceback when trying to add alternative from scenario -pivot view

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2580]
In the scenario pivot view trying to add a new alternative by typing it in a cell will result in the following traceback:

```
Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox\helpers.py", line 123, in new_function
    return func(*args, **kwargs)
  File "C:\spine-toolbox\spinetoolbox\fetch_parent.py", line 102, in _apply_pending_changes
    last_handler({db_map: items})
  File "C:\spine-toolbox\spinetoolbox\fetch_parent.py", line 325, in handle_items_added
    self._handle_items_added(db_map_data)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 1035, in _handle_alternatives_added
    self.add_to_model(data)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 479, in add_to_model
    frozen_values = self.model.frozen_values(db_map_data)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\pivot_model.py", line 115, in frozen_values
    frozen_getter = self._index_key_getter(self.pivot_frozen)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\pivot_model.py", line 151, in _index_key_getter
    return tuple_itemgetter(operator.itemgetter(*keys), len(keys))
TypeError: itemgetter expected 1 argument, got 0
python-BaseException
```

**Comment by manuelma** [comment]
Doesn't happen anymore? Or I'm missing something?

**Comment by PiispaH** [comment]
Can't reproduce anymore
