### ISSUE TITLE
Can't open right click context menu for items in graph view

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2594]
In 0.8-dev right clicking an item in graph view results in a traceback:

```
Traceback (most recent call last):
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\widgets\custom_qgraphicsviews.py", line 890, in contextMenuEvent
    super().contextMenuEvent(e)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\graphics_items.py", line 573, in contextMenuEvent
    menu = self._make_menu()
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\graphics_items.py", line 551, in _make_menu
    self._refresh_db_map_entity_class_lists()
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\graphics_items.py", line 625, in _refresh_db_map_entity_class_lists
    db_map_entity_class_ids = {db_map: self.entity_class_ids(db_map) for db_map in self.db_maps}
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\graphics_items.py", line 625, in <dictcomp>
    db_map_entity_class_ids = {db_map: self.entity_class_ids(db_map) for db_map in self.db_maps}
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\graphics_items.py", line 177, in entity_class_ids
    for x in db_map.get_items("superclass_subclass", subclass_id=self.entity_class_id(db_map))
  File "C:\toolbox\src\spinedb-api\spinedb_api\db_mapping.py", line 387, in get_items
    self.do_fetch_more(item_type, offset=0, limit=None, **kwargs)
  File "C:\toolbox\src\spinedb-api\spinedb_api\db_mapping_base.py", line 300, in do_fetch_more
    chunk = self._get_next_chunk(item_type, offset, limit, **kwargs)
  File "C:\toolbox\src\spinedb-api\spinedb_api\db_mapping_base.py", line 288, in _get_next_chunk
    return [dict(x) for x in qry]
  File "C:\toolbox\src\spinedb-api\spinedb_api\query.py", line 138, in __iter__
    return self._result() or iter([])
  File "C:\toolbox\src\spinedb-api\spinedb_api\query.py", line 103, in _result
    return self._bind.execute(self._select)
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\base.py", line 2235, in execute
    return connection.execute(statement, *multiparams, **params)
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "C:\toolbox\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "C:\toolbox\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\toolbox\lib\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT superclass_subclass_sq.id, superclass_subclass_sq.superclass_id, superclass_subclass_sq.subclass_id 
FROM (SELECT superclass_subclass.id AS id, superclass_subclass.superclass_id AS superclass_id, superclass_subclass.subclass_id AS subclass_id 
FROM superclass_subclass) AS superclass_subclass_sq 
WHERE superclass_subclass_sq.subclass_id = ?]
[parameters: (TempId(entity_class) resolved to 5,)]
(Background on this error at: http://sqlalche.me/e/13/rvf5)
```

**Comment by manuelma** [comment]
Thanks!
I also saw this and am testing a fix...

**Comment by manuelma** [comment]
Should be fixed by this https://github.com/spine-tools/Spine-Database-API/commit/549b2cb0fb656ff8299115b8535d3ff18f252407
