### ISSUE TITLE
Deleting entity group causes traceback

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2596]
Adding an entity group, committing then deleting the group:

```
Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox\helpers.py", line 123, in new_function
    return func(*args, **kwargs)
  File "C:\spine-toolbox\spinetoolbox\fetch_parent.py", line 102, in _apply_pending_changes
    last_handler({db_map: items})
  File "C:\spine-toolbox\spinetoolbox\fetch_parent.py", line 330, in handle_items_removed
    self._handle_items_removed(db_map_data)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\entity_tree_item.py", line 316, in _handle_entity_group_items_removed
    self.parent_item.reposition_child(self.child_number())
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\multi_db_tree_item.py", line 454, in reposition_child
    self._insert_children_sorted([child])
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\multi_db_tree_item.py", line 291, in _insert_children_sorted
    for chunk, pos in bisect_chunks(self.children, new_children, key=self._children_sort_key):
  File "C:\spine-toolbox\spinetoolbox\helpers.py", line 1475, in bisect_chunks
    lo = bisect.bisect_left(current_data, key(item))
TypeError: '<' not supported between instances of 'str' and 'NoneType'
```

Similar traceback mentioned also in #2575.

**Comment by manuelma** [comment]
Fixed by https://github.com/spine-tools/Spine-Toolbox/commit/c19e678833d4e71e0cd8c5d9de37bae270b33bec
