### ISSUE TITLE
Traceback when switching project

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2706]
I had just ran a Python Tool (Flextool) that failed and caused the kernel to die. After that I tried to switch projects but the new project wouldn't load and this was lurking in my console:

```
Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox\helpers.py", line 124, in new_function
    return func(*args, **kwargs)
  File "C:\spine-toolbox\spinetoolbox\fetch_parent.py", line 99, in _apply_pending_changes
    last_handler({db_map: items})
  File "C:\spine-toolbox\spinetoolbox\fetch_parent.py", line 322, in handle_items_added
    self._handle_items_added(db_map_data)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\tree_item_utility.py", line 198, in handle_items_added
    self.insert_children(len(self.non_empty_children), children_uncommitted)
  File "C:\spine-toolbox\spinetoolbox\mvcmodels\minimal_tree_model.py", line 153, in insert_children
    parent_index = self.index()
  File "C:\spine-toolbox\spinetoolbox\mvcmodels\minimal_tree_model.py", line 124, in index
    return self.model.index_from_item(self)
  File "C:\spine-toolbox\spinetoolbox\mvcmodels\minimal_tree_model.py", line 313, in index_from_item
    return self.createIndex(row, 0, item)
RuntimeError: Internal C++ object (ScenarioModel) already deleted.
Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox\widgets\custom_menus.py", line 154, in <lambda>
    lambda checked=False, filepath=filepath: self.call_open_project(checked, filepath),
  File "C:\spine-toolbox\spinetoolbox\widgets\custom_menus.py", line 188, in call_open_project
    if not self._parent.open_project(p):
  File "C:\spine-toolbox\spinetoolbox\ui_main.py", line 565, in open_project
    success = self.restore_project(load_dir)
  File "C:\spine-toolbox\spinetoolbox\ui_main.py", line 582, in restore_project
    if not self.close_project(ask_confirmation):
  File "C:\spine-toolbox\spinetoolbox\ui_main.py", line 756, in close_project
    self.clear_ui()
  File "C:\spine-toolbox\spinetoolbox\ui_main.py", line 852, in clear_ui
    self._shutdown_engine_kernels()
  File "C:\spine-toolbox\spinetoolbox\ui_main.py", line 2468, in _shutdown_engine_kernels
    engine_mngr.kill_persistent(key)
  File "C:\spine-toolbox\spinetoolbox\spine_engine_manager.py", line 209, in kill_persistent
    kill_persistent(persistent_key)
  File "C:\toolbox\src\spine-engine\spine_engine\execution_managers\persistent_execution_manager.py", line 743, in kill_persistent
    _persistent_manager_factory.kill_persistent(key)
  File "C:\toolbox\src\spine-engine\spine_engine\execution_managers\persistent_execution_manager.py", line 646, in kill_persistent
    pm.kill_process()
  File "C:\toolbox\src\spine-engine\spine_engine\execution_managers\persistent_execution_manager.py", line 452, in kill_process
    self._release_persistent_resources()
  File "C:\toolbox\src\spine-engine\spine_engine\execution_managers\persistent_execution_manager.py", line 459, in _release_persistent_resources
    self._persistent.stdin.close()
OSError: [Errno 22] Invalid argument
```

**Comment by jkiviluo** [comment]
Couldn't replicate exactly this. If I kill the solver process from the task manager during FlexTool execution (run a model that takes some time), the kernel dies, but I don't get the tracebacks above even if I switch project. 

There is a bug that the tool keeps hammering even though execution has stopped. Everything else works though. There is a different traceback from this:

```
Traceback (most recent call last):
  File "C:\sources\spine-toolbox\spinetoolbox\ui_main.py", line 2203, in _stop_execution
    self._project.stop()
  File "C:\sources\spine-toolbox\spinetoolbox\project.py", line 1214, in stop
    worker.stop_engine()
  File "C:\sources\spine-toolbox\spinetoolbox\spine_engine_worker.py", line 167, in stop_engine
    self._engine_mngr.stop_engine()
  File "C:\sources\spine-toolbox\spinetoolbox\spine_engine_manager.py", line 157, in stop_engine
    self._engine.stop()
  File "C:\sources\spine-toolbox\src\spine-engine\spine_engine\spine_engine.py", line 353, in stop
    self._stop_item(item)
  File "C:\sources\spine-toolbox\src\spine-engine\spine_engine\spine_engine.py", line 358, in _stop_item
    item.stop_execution()
  File "C:\sources\spine-toolbox\src\spine-items\spine_items\tool\executable_item.py", line 146, in stop_execution
    self._tool_instance.terminate_instance()
  File "C:\sources\spine-toolbox\src\spine-items\spine_items\tool\tool_instance.py", line 66, in terminate_instance
    self.exec_mngr.stop_execution()
  File "C:\sources\spine-toolbox\src\spine-engine\spine_engine\execution_managers\persistent_execution_manager.py", line 848, in stop_execution
    self._persistent_manager.interrupt_persistent()
  File "C:\sources\spine-toolbox\src\spine-engine\spine_engine\execution_managers\persistent_execution_manager.py", line 415, in interrupt_persistent
    self._wait()
  File "C:\sources\spine-toolbox\src\spine-engine\spine_engine\execution_managers\persistent_execution_manager.py", line 287, in _wait
    success = self._persistent.returncode == 0
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'returncode'
```
