### ISSUE TITLE
Traceback from graph view by selecting entity class

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2728]
This doesn't happen on all databases but for example in this [Data Store (5).zip](https://github.com/spine-tools/Spine-Toolbox/files/15146288/Data.Store.5.zip) database, selecting any entity or entity class in graph view will cause the following traceback:

```
Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox\helpers.py", line 124, in new_function
    return func(*args, **kwargs)
  File "C:\spine-toolbox\spinetoolbox\fetch_parent.py", line 99, in _apply_pending_changes
    last_handler({db_map: items})
  File "C:\spine-toolbox\spinetoolbox\fetch_parent.py", line 322, in handle_items_added
    self._handle_items_added(db_map_data)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\widgets\graph_view_mixin.py", line 195, in _graph_handle_entities_added
    self._refresh_graph()
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\widgets\graph_view_mixin.py", line 489, in _refresh_graph
    self._update_graph_data()
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\widgets\graph_view_mixin.py", line 570, in _update_graph_data
    self._entity_fetch_parent.bind_item(item, db_map)
  File "C:\spine-toolbox\spinetoolbox\fetch_parent.py", line 106, in bind_item
    item.add_restore_callback(self._make_restore_item_callback(db_map))
TypeError: 'NoneType' object is not callable
```

When this happens nothing is drawn. If the root is selected, everything is drawn correctly and no traceback is present.

**Comment by PiispaH** [comment]
Fixed by above commits.
