### ISSUE TITLE
After one successful execution the execution won't stop, even though it is finnished

### ISSUE THREAD

**Issue by ArttuTupala** [spine-tools/Spine-Toolbox#2732]
After running a successful scenario. (Results have come to the database), the toolbox thinks that the workflow is still running and won't allow running new a DAG. Stop button first tries to stop, but then thinks that the run is over (as it is), but won't solve the issue. Additionally the exclamation mark for the missing input data won't clear, even though it just run a perfectly good model. Done with Flextool workflow and database upgraded to 0.8. Can be re-created every time.
![image](https://github.com/spine-tools/Spine-Toolbox/assets/84875787/2a3da9b6-a891-4c0c-a370-ed389ead2119)

**Comment by ArttuTupala** [comment]
Fixed by deleting export_manifests.

Traceback (most recent call last):
  File "C:\Users\AETART\Documents\Spinetoolbox\Spine-Toolbox\src\spine-items\spine_items\data_store\data_store.py", line 423, in _accept_url
    self._resources_to_successors_changed()
  File "C:\Users\AETART\Documents\Spinetoolbox\Spine-Toolbox\spinetoolbox\project_item\project_item.py", line 283, in _resources_to_successors_changed
    self._project.notify_resource_changes_to_successors(self)
  File "C:\Users\AETART\Documents\Spinetoolbox\Spine-Toolbox\spinetoolbox\project.py", line 1244, in notify_resource_changes_to_successors
    self._notify_resource_changes(
  File "C:\Users\AETART\Documents\Spinetoolbox\Spine-Toolbox\spinetoolbox\project.py", line 1271, in _notify_resource_changes
    update_resources(target_item, connections, resource_cache)
  File "C:\Users\AETART\Documents\Spinetoolbox\Spine-Toolbox\spinetoolbox\project.py", line 1432, in _update_successor
    successor.upstream_resources_updated(combined_resources)
  File "C:\Users\AETART\Documents\Spinetoolbox\Spine-Toolbox\src\spine-items\spine_items\exporter\exporter.py", line 212, in upstream_resources_updated
    self._resources_to_successors_changed()
  File "C:\Users\AETART\Documents\Spinetoolbox\Spine-Toolbox\spinetoolbox\project_item\project_item.py", line 283, in _resources_to_successors_changed
    self._project.notify_resource_changes_to_successors(self)
  File "C:\Users\AETART\Documents\Spinetoolbox\Spine-Toolbox\spinetoolbox\project.py", line 1243, in notify_resource_changes_to_successors
    trigger_resources = item.resources_for_direct_successors()
  File "C:\Users\AETART\Documents\Spinetoolbox\Spine-Toolbox\src\spine-items\spine_items\exporter\exporter.py", line 407, in resources_for_direct_successors
    resources, self._exported_files = exported_files_as_resources(
  File "C:\Users\AETART\Documents\Spinetoolbox\Spine-Toolbox\src\spine-items\spine_items\exporter\export_manifest.py", line 35, in exported_files_as_resources
    manifests = _collect_execution_manifests(data_dir)
  File "C:\Users\AETART\Documents\Spinetoolbox\Spine-Toolbox\src\spine-items\spine_items\exporter\export_manifest.py", line 73, in _collect_execution_manifests
    manifest = json.load(manifest_file)
  File "C:\Users\AETART\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\AETART\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\AETART\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\AETART\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
