### ISSUE TITLE
Traceback when entity item is selected and imported with purge

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2842]
To reproduce:
1. Import some entities and parameter values into a db.
2. Open db editor and select one of the added entities form **Entity tree**
3. Run the Importer again with the link set to purge the items -> traceback

```
Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\widgets\stacked_view_mixin.py", line 198, in _handle_entity_tree_selection_changed_in_parameter_tables
    self._set_default_parameter_data(self.ui.treeView_entity.selectionModel().currentIndex())
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\widgets\stacked_view_mixin.py", line 120, in _set_default_parameter_data
    default_data = item.default_parameter_data()
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\entity_tree_item.py", line 264, in default_parameter_data
    entity_byname=DB_ITEM_SEPARATOR.join(self.db_map_data_field(self.first_db_map, "entity_byname")),
TypeError: can only join an iterable
```

**Comment by PiispaH** [comment]
Doesn't happen anymore. Traceback is the same as in #2872 so fixed there or somewhere else possibly.
