### ISSUE TITLE
Traceback when pressing delete in add entities dialog

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2880]
```
Traceback (most recent call last):
  File "C:\spinetoolbox\widgets\custom_qtableview.py", line 101, in delete_content
    return self.model().batch_set_data(indexes, len(indexes) * [None])
  File "C:\spinetoolbox\spine_db_editor\mvcmodels\empty_models.py", line 351, in batch_set_data
    self._main_data[row][column] = self._parent.construct_composite_class_name(index.row())
AttributeError: 'AddEntitiesDialog' object has no attribute 'construct_composite_class_name'
```

**Comment by soininen** [comment]
Please use `spinedb_api.helpers.name_from_dimensions()` (entity classes) and `spinedb_api.helpers.name_from_elements()` (entities) if automatic naming is needed.
