### ISSUE TITLE
Traceback when closing db editor

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2894]
1. Open a db with atleast one entity alternative or paremeter already committed.
2. Double click any of the cells from the defined entity alternative/parameter to open the dropdown list of available items.
3. Close the editor -> traceback:

```
Traceback (most recent call last):
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\widgets\custom_qtableview.py", line 72, in _set_data
    index.model().setData(index, new_value)
  File "C:\spine-toolbox\spinetoolbox\mvcmodels\minimal_table_model.py", line 151, in setData
    return self.batch_set_data([index], [value])
  File "C:\spine-toolbox\spinetoolbox\mvcmodels\compound_table_model.py", line 200, in batch_set_data
    if not model.batch_set_data(list(indexes), list(values)):
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\single_models.py", line 243, in batch_set_data
    self.update_items_in_db(items)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\single_models.py", line 361, in update_items_in_db
    super().update_items_in_db(items)
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\single_models.py", line 95, in update_items_in_db
    self._do_update_items_in_db({self.db_map: items_to_upd})
  File "C:\spine-toolbox\spinetoolbox\spine_db_editor\mvcmodels\single_models.py", line 430, in _do_update_items_in_db
    self.db_mngr.update_entity_alternatives(db_map_data)
  File "C:\spine-toolbox\spinetoolbox\spine_db_manager.py", line 1161, in update_entity_alternatives
    self.update_items("entity_alternative", db_map_data)
  File "C:\spine-toolbox\spinetoolbox\spine_db_manager.py", line 1363, in update_items
    self.undo_stack[db_map].push(
KeyError: <spinedb_api.db_mapping.DatabaseMapping object at 0x00000209D249E670>
```

**Comment by jkiviluo** [comment]
I don't see this happening either on Linux or Windows. Maybe it's been fixed by other changes.
