### ISSUE TITLE
Importers stuck

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2940]
### Discussed in https://github.com/spine-tools/Spine-Toolbox/discussions/2939

<div type='discussions-op-text'>

<sup>Originally posted by **Mastomaki** September 27, 2024</sup>

Four importers get stuck when I run my whole project. I can run them individually without problems. Here is the error message:

```
>spinetoolbox
Exception in thread Thread-91 (_do_work):
Traceback (most recent call last):
  File "/home/jube/anaconda3/envs/spinetb08/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/jube/anaconda3/envs/spinetb08/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jube/data/spine/versions/v08/Spine-Toolbox/src/spinedb-api/spinedb_api/spine_db_server.py", line 372, in _do_work
    result = handler(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jube/data/spine/versions/v08/Spine-Toolbox/src/spinedb-api/spinedb_api/spine_db_server.py", line 402, in _do_import_data
    count, errors = import_data(self._db_map, unparse_value=_unparse_value, **data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jube/data/spine/versions/v08/Spine-Toolbox/src/spinedb-api/spinedb_api/import_functions.py", line 85, in import_data
    added, updated, errors = db_map.add_update_items(item_type, *items, strict=False)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jube/data/spine/versions/v08/Spine-Toolbox/src/spinedb-api/spinedb_api/import_functions.py", line 649, in _get_parameter_values_for_import
    pv = db_map.mapped_table("parameter_value").find_item(item)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jube/data/spine/versions/v08/Spine-Toolbox/src/spinedb-api/spinedb_api/db_mapping_base.py", line 463, in find_item
    return self.find_item_by_unique_key(item, skip_keys=skip_keys, fetch=fetch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jube/data/spine/versions/v08/Spine-Toolbox/src/spinedb-api/spinedb_api/db_mapping_base.py", line 480, in find_item_by_unique_key
    current_item = self._find_fully_qualified_item_by_unique_key(item, skip_keys, fetch, valid_only)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jube/data/spine/versions/v08/Spine-Toolbox/src/spinedb-api/spinedb_api/db_mapping_base.py", line 474, in _find_fully_qualified_item_by_unique_key
    current_item = self._unique_key_value_to_item(key, value, fetch=fetch, valid_only=valid_only)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jube/data/spine/versions/v08/Spine-Toolbox/src/spinedb-api/spinedb_api/db_mapping_base.py", line 424, in _unique_key_value_to_item
    id_ = self._unique_key_value_to_id(key, value, fetch=fetch)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jube/data/spine/versions/v08/Spine-Toolbox/src/spinedb-api/spinedb_api/db_mapping_base.py", line 419, in _unique_key_value_to_id
    self._db_map.do_fetch_all(self._item_type)
  File "/home/jube/data/spine/versions/v08/Spine-Toolbox/src/spinedb-api/spinedb_api/db_mapping_base.py", line 372, in do_fetch_all
    self.do_fetch_more(item_type, offset=0, limit=None, real_commit_count=commit_count)
  File "/home/jube/data/spine/versions/v08/Spine-Toolbox/src/spinedb-api/spinedb_api/db_mapping_base.py", line 342, in do_fetch_more
    item.become_referrer()
  File "/home/jube/data/spine/versions/v08/Spine-Toolbox/src/spinedb-api/spinedb_api/db_mapping_base.py", line 1128, in become_referrer
    add_self_as_referrer(field_value)
  File "/home/jube/data/spine/versions/v08/Spine-Toolbox/src/spinedb-api/spinedb_api/db_mapping_base.py", line 1116, in add_self_as_referrer
    raise RuntimeError(f"Reference id {ref_id} not found")
RuntimeError: Reference id 98 not found

```</div>

**Comment by soininen** [comment]
@Mastomaki Can you check if this issue still persists? Pull request spine-tools/Spine-Database-API#452 may have fixed it. If you still get the Traceback, we need to take a closer look how your workflow has been set up exactly.

**Comment by Mastomaki** [comment]
It still doesn't work. Same kind of error message.
