### ISSUE TITLE
Windows 8.1 traceback

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#3014]
Trying to start Toolbox (latest, all packages up-to-date, the same bundle works on Windows11)

Traceback (most recent call last):
  File "spinetoolbox.py", line 20, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "spinetoolbox\main.py", line 27, in <module>
ImportError: DLL load failed while importing QtGui: Le module spécifié est introuvable.

**Comment by ptsavol** [comment]
Qt6 does not support Windows 8.1 anymore so there's no help coming there. Is this a 32-bit or 64-bit Win8.1? You may want to check that the bitness matchess with the Python bitness.

Any chance of upgrading to Win 10?

**Comment by jkiviluo** [comment]
I don't think that's an option in general for older computers. If they are to have a new life, it's probably better to switch to Linux. And in that case, there is a chance also Toolbox would work.

I keep this issue open until we have updated somewhere visible which OS versions we support.
